<?php
/**
 * @file
 * Code for the KTC - Arrangement feature.
 */

include_once 'ktc_arrangement.features.inc';

/**
 * Implements hook_signup_close.
 */
function ktc_arrangement_signup_close($node){
 entity_get_controller('node')->resetCache(array($node->nid));
}

/**
 * Implements hook_signup_open.
 */
function ktc_arrangement_signup_open($node){
 entity_get_controller('node')->resetCache(array($node->nid));
}

function ktc_arrangement_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'arrangement_node_form'){
    global $user;
    if($user->uid == 0){
      unset($form['#groups']['group_groups']);
      unset($form['#fieldgroups']['group_groups']);
      unset($form['#groups']['group_arrangementbesk']);
      unset($form['#fieldgroups']['group_arrangementbesk']);
    }
    return $form;
  }
}