<?php
/**
 * @file
 * Code for the KTC sectionpage module.
 */

/**
 * Implements hook_menu().
 */
function ktc_sectionpage_menu() {
  $items['ajax/%/view/%/%/%/%/%/%'] = array(
    'page callback' => 'ktc_sectionpage_ajax_view',
    'access arguments' => array('access content'),
    'page arguments' => array(1, 3, 4, 5, 6, 7, 8),
  );
  $items['ajax/pane/subterms/view/%'] = array(
    'page callback' => 'ktc_subterms_filters_ajax_view',
    'access arguments' => array('access content'),
     'page arguments' => array(4,5)
  );
  $items['all_groups/%/%/%/%/%'] = array(
    'page callback' => 'ktc_sectionpage_ajax_all_groups_view',
    'access arguments' => array('access content'),
    'page arguments' => array(1, 2, 3, 4, 5),
  );

  $items['user/group/new_content'] = array(
    'page callback' => 'ktc_sectionpage_redirect_link',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(2),
  );

  $items['user/user_comments'] = array(
    'page callback' => 'ktc_sectionpage_redirect_link',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(1),
  );
  return $items;
}

/**
 * User menus callback.
 */
function ktc_sectionpage_redirect_link($page) {
  global $user;
  $goto = FALSE;
  switch ($page) {
    case 'new_content':
      $goto = 'user/' . $user->uid . '/group/new_content';
      break;

    case 'user_comments':
      $goto = 'user/' . $user->uid . '/user_comments';
      break;
  }

  if ($goto) {
    drupal_goto($goto);
  }
}

/**
 * All groups ajax view call back.
 */
function ktc_sectionpage_ajax_all_groups_view($f1, $f2, $f3, $f4, $f5 = 'all') {
  $term_type = _ktc_sectionpage_filter_helper($f1);
  $emner = _ktc_sectionpage_filter_helper($f2);
  $tags = _ktc_sectionpage_filter_helper($f3);
  $regioner = _ktc_sectionpage_filter_helper($f4);
  $view = views_get_view('section_page_filter_extra');

  switch ($f5) {
    case 'my,':
      $view->set_display('panel_pane_3');
      $f5_value = _ktc_sectionpage_group_filter_helper($f5);
      $view->set_arguments(array($term_type, $emner, $tags, $regioner, $f5_value));
      break;

    case 'all,':
      $view->set_display('panel_pane_3');
      $f5_value = _ktc_sectionpage_group_filter_helper($f5);
      $view->set_arguments(array($term_type, $emner, $tags, $regioner, $f5_value));
      break;
  }

  if ($f5 == 'newest') {
    $view->set_display('panel_pane_1');
    $view->set_arguments(array($term_type, $emner, $tags, $regioner, 'all'));
    $view->pre_execute();
    $view->execute();
    print $view->render('panel_pane_1');
  }
  else {
    $view->pre_execute();
    $view->execute();
    print $view->render('panel_pane_3');
  }

}

/**
 * Default ajax view call back.
 *
 * @param string $page
 *   last part in the url.
 *        string $f1 content_type
 *        string $f2: term_type (like document type, group type, news type ...)
 *        (arrangement type)
 *        string $f3: emner (field_topics) (period in arrangement page)
 *        string $f4: tags (field_tags) (date in arrangement page)
 *        string $f5: regioner
 *        string $gid: group ids.
 */
function ktc_sectionpage_ajax_view($page, $f1, $f2, $f3, $f4, $f5, $gid) {

  $output = _ktc_content_filter_view($page, $f1, $f2, $f3, $f4, $f5, $gid);

  if ($page == 'aktiviteter' || arg(0) == 'aktiviteter') {
    // $f2 in "aktiviteter" page is arrangement type term,
    // $f3 in "aktiviteter" page is period, as "fulture" or "old"
    // $4 is date, like 2014-12-16.
    $output = _ktc_section_block_arrangement_content($f2, $f3, $f4);
  }

  if ($page == 'hoeringer' || arg(0) == 'hoeringer') {
    $output = _ktc_section_block_hearing_content($f1, $f2, $f3, $f4, $f5, $gid);
  }
  
  if ($page == 'teknikmiljoe' || arg(0) == 'teknikmiljoe') {
    $output = _ktc_section_block_magazine_content($page, $f1, $f2, $f3, $f4, $f5, $gid);
  }
  print $output;

}

function ktc_subterms_filters_ajax_view($voc_id, $parent_id){   
  $parent_terms = _ktc_sectionpage_filter_helper($parent_id);
  $level = _ktc_sectionpage_helper_get_term_depth($parent_id);
  $view = views_get_view('section_page_filter');
  $view->set_display('panel_pane_4');
  $view->set_arguments(array($voc_id, $parent_terms));
  $view->pre_execute();
  $view->execute();
  if (count( $view->result )>0) {
  $output = '<div class="ktc-aside panel-pane pane-views-panes pane-section-page-filter-panel-pane-3 ktc-aside-checkbox-filter" id="emner-'.$level .'">
                <div class="ktc-aside-heading">
                    <h3 class="ktc-aside-title">Filtrer på faglige emner</h3>
                 </div>        
                <div class="ktc-aside-body pane-content">';
 $output .= $view->render('panel_pane_4');
 $output .='</div></div>';
 print $output;
 }
}

/****************  ktc_sectionpage.module blocks *********************/

/**
 * Implements hook_block_info().
 */
function ktc_sectionpage_block_info() {
  $blocks = array();

  $blocks['arrangement_page_block'] = array(
    'info' => t('Aktiviteter side block'),
  );

  $blocks['hearing_page_block'] = array(
    'info' => t('Høringer side block'),
  );
  
  $blocks['magazine_page_block'] = array(
    'info' => t('KTC Udgivelse side block'),
  );

  $blocks['netvaerk_invite_links'] = array(
    'info' => t('Netvaerk invite links'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['section_default_content'] = array(
    'info' => t('KTC sektionsside standard indhold'),
  );

  $blocks['user_comments_block'] = array(
    'info' => t('KTC brugere kommentarter blok'),
  );

  $blocks['user_comments_block_2'] = array(
    'info' => t('KTC lille kommentarter blok'),
  );

  $blocks['custom_filter_on_hearing'] = array(
    'info' => t('KTC filtrer på høringer blok'),
  );
  $blocks['date_filter_on_magazine'] = array(
    'info' => t('KTC date filtrer udgivelse indholdstyper'),
  );

  $blocks['netvaerk_content_types'] = array(
    'info' => t('KTC filtrer netværk indholdstyper'),
  );

  $blocks['ktc_page_menu_tabs'] = array(
    'info' => t('Page menu tabs'),
  );

  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function ktc_sectionpage_block_view($delta = '') {
  $block = array();
  switch ($delta) {

    case 'arrangement_page_block':
      $block['subject'] = '';
      $block['content'] = _ktc_section_block_arrangement_content();
      break;

    case 'hearing_page_block':
      $block['subject'] = '';
      $block['content'] = _ktc_section_block_hearing_content();
      break;
  
    case 'magazine_page_block':
      $block['subject'] = '';
      $block['content'] = _ktc_section_block_magazine_content();
      break;

    case 'netvaerk_invite_links':
      $block['subject'] = '';
      $block['content'] = _ktc_section_block_netvaerk_invite_links_content();
      break;

    case 'section_default_content':
      $block['subject'] = '';
      $block['content'] = _ktc_content_filter_view();
      break;

    case 'user_comments_block':
      $block['subject'] = '';
      $block['content'] = _ktc_user_comments_content(TRUE);
      break;

    case 'user_comments_block_2':
      $block['subject'] = '';
      $block['content'] = _ktc_user_comments_content(FALSE);
      break;

    case 'custom_filter_on_hearing':
      $block['subject'] = t('Filtrer på høringer');
      $block['content'] = _ktc_custom_filter_on_hearing();
      break;
  
    case 'date_filter_on_magazine':
      $block['subject'] = t('Filtrer på udgivelse ');
      $block['content'] = _ktc_date_filter_on_magazine();
      break;

    case 'netvaerk_content_types':
      $block['subject'] = '';
      $block['content'] = _ktc_section_block_netvaerk_content_types();
      break;

    case 'ktc_page_menu_tabs':
      $block['subject'] = '';
      $block['content'] = _ktc_section_block_page_menu_tabs();
      break;
  }
  return $block;
}
/**
 * Arrangement block_view call back.
 */
function _ktc_section_block_arrangement_content($f2 = 'all', $f3 = 'fulture', $f4 = 'all') {
  $filter_ar = explode(',', $f2);
  $filter = '';

  foreach ($filter_ar as $value) {
    if ($value == 'all' || $value == '') {
      continue;
    }
    if (is_numeric($tid = str_replace('tid-', '', $value))) {
      if ($term = taxonomy_term_load($tid)) {
        if ($filter == '') {
          $filter = $tid;
        }
        else {
          $filter .= '+' . $tid;
        }
      }
    }

  }
  if ($filter == '') {
    $filter = 'all';
  }

  $view = views_get_view('arrangement');
  if ($f3 == 'old') {
    $view->set_display('block_4');
  }
  else {
    $view->set_display('block_3');
  }

  $view->set_arguments(array($filter, $f4));
  $view->pre_execute();
  $view->execute();
  if ($f3 == 'old') {
    return $view->render('block_4');
  }
  else {
    return $view->render('block_3');
  }

}

/**
 * Hearing block_view call back.
 *
 * @param string $f1
 *   term_type (hearing_type)
 *    $f2 emner
 *    $f3 user (all or mine)
 *    $4 hearing_status (open or 1840)
 *    $f5 year (all or year nummbers.)
 */
function _ktc_section_block_hearing_content($type = 'hearing', $f1 = '', $f2 = '', $f3 = '', $f4 = 'all', $f5 = 'all') {
  global $user;
  $term_type = _ktc_sectionpage_filter_helper($f1);
  $emner = _ktc_sectionpage_filter_helper($f2);
  $uid = ($f3 == 'mine') ? $user->uid : 'all';
  $status = (is_numeric($f4)) ? $f4 : 'all';
  $nids = _ktc_sectionpage_years_filter_helper($f5);
  $view = views_get_view('indhold_m_filter');
  $view->set_display('panel_pane_3');
  $view->set_arguments(array('all', $nids, $uid, $status, $term_type, $emner));
  $view->pre_execute();
  $view->execute();
  return $view->render('panel_pane_3');

}

/**
 * Hearing block_view call back.
 *
 * @param string $f1
 *   term_type (hearing_type)
 *    $f2 emner
 *    $f3 user (all or mine)
 *    $4 hearing_status (open or 1840)
 *    $f5 year (all or year nummbers.)
 */
function _ktc_section_block_magazine_content($page = '', $f1 = 'magazine', $f2 = '', $f3 = '', $f4 = '', $f5 = '', $gid = '') {
  $content_type = _ktc_sectionpage_filter_helper($f1);
  $term_type = _ktc_sectionpage_filter_helper($f2);
  $emner = _ktc_sectionpage_filter_helper($f3);
 /*$tags = _ktc_sectionpage_filter_helper($f4);
  $regioner = _ktc_sectionpage_filter_helper($f5);*/
  $nids = _ktc_sectionpage_magazine_years_filter_helper($f3, $f4);
  $gid = _ktc_sectionpage_group_filter_helper($gid);
  $view = views_get_view('indhold_m_filter');
  $view->set_display('panel_pane_7');
  $view->set_arguments(array($content_type, $term_type,  $nids, $gid));
  $view->pre_execute();
  $view->execute();
  return $view->render('panel_pane_7');

}
/**
 * Group invite link block_view call back.
 */
function _ktc_section_block_netvaerk_invite_links_content() {
  $nid = arg(1);
  $html = '';
  if (is_numeric($nid) && user_is_logged_in()) {
    $html .= '<div class="row">';
    $link_class = 'filter-link btn btn-default';
    $node = node_load($nid);
    $og_is_member = og_is_member('node', $nid);

    // If user has access to invite user to group.
    if ($access = og_user_access('node', $nid, 'invite any user') && $og_is_member) {
      $html .= '<div class="ktc-filter-button-container og-members-modal">';
      $html .= l('Invitér', '', array('attributes' => array('class' => $link_class)));
      $html .= '</div>';
    }
    // Check if the user is a member,
    // print out subscrib/unsubscrib link.
    if (og_user_access('node', $nid, 'unsubscribe') && $og_is_member) {
      $html .= '<div class="ktc-filter-button-container">';
      $html .= l('Afmeld', 'group/node/' . $nid . '/unsubscribe', array('attributes' => array('class' => $link_class)));
      $html .= '</div>';
    }
    if (!$og_is_member) {
      if (og_user_access('node', $nid, 'subscribe without approval')) {
        $html .= '<div class="ktc-filter-button-container">';
        $html .= l('Ansøg om medlemskab', 'group/node/' . $nid . '/subscribe', array('attributes' => array('class' => $link_class)));
        $html .= '</div>';
      }
      else if (og_user_access('node', $nid, 'subscribe')) {
        $html .= '<div class="ktc-filter-button-container">';
        $html .= l('Tilmeld', 'group/node/' . $nid . '/subscribe', array('attributes' => array('class' => $link_class)));
        $html .= '</div>';
      }
    }
    $html .= '</div>';
  }
  return $html;
}
/**
 * Custom filter block on hearing section page.
 */
function _ktc_custom_filter_on_hearing() {
  global $user;
  $html = '<div id="filter-box-hearing-extra" class="filter-box">';
  if ($user->uid != 0) {
    $html .= '
      <div class="ktc-filter-button-container">
        <div class="btn btn-default filter-link" id="filter-all" data-filter="all">Alle</div>
      </div>
      <div class="ktc-filter-button-container">
        <div class="btn btn-default filter-link filter-status" id="filter-status" data-filter="1837">Åbne</div>
      </div>
      <div class="ktc-filter-button-container">
        <div class="btn btn-default filter-link" id="filter-mine" data-filter="mine">Mine</div>
      </div>
      <div class="ktc-filter-button-container">
        <div class="btn btn-default filter-link filter-status" id="filter-status" data-filter="1840">Lukkede</div>
      </div>';

  }
  $years = _ktc_sectionpage_get_hearing_years();
  if (!empty($years)) {
    foreach ($years as $key => $year) {
      $html .= '
        <div class="ktc-filter-button-container">
          <div class="btn btn-default filter-link" id="filter-year" data-filter="' . $key . '">' . $key . '</div>
        </div>';
    }
  }
  $html .= '</div>';
  return $html;
}

/**
 * Data filter block on teknikmiljoe section page.
 */
function _ktc_date_filter_on_magazine() {
  
  $html = '<div id="filter-box-magazine-date" class="filter-box">';
    $html .= '
      <div class="ktc-filter-button-container">
        <div class="btn btn-default filter-link" id="filter-all" data-filter="all">Alle</div>
      </div>';
  $years = _ktc_sectionpage_get_magazine_years();
  $month = _ktc_sectionpage_get_magazine_month();
  if (!empty($years)) {
    foreach ($years as $key => $year) {
      $html .= '
        <div class="ktc-filter-button-container">
          <div class="btn btn-default filter-link" id="filter-year" data-filter="' . $key . '">' . $key . '</div>
        </div>';
    }
  }

   if (!empty($month)) {
    foreach ($month as $key => $month) {
      $html .= '
        <div class="ktc-filter-button-container">
          <div class="btn btn-default filter-link" id="filter-month" data-filter="' . $key . '">' . $key . '</div>
        </div>';
    }
  }
  $html .= '</div>';
  return $html;
}
/**
 * Default filter block_view call back.
 */
function _ktc_content_filter_view($page = '', $f1 = '', $f2 = '', $f3 = '', $f4 = '', $f5 = '', $gid = '') {
  $content_type = _ktc_sectionpage_filter_helper($f1);
  $term_type = _ktc_sectionpage_filter_helper($f2);
  $emner = _ktc_sectionpage_filter_helper($f3);
  $tags = _ktc_sectionpage_filter_helper($f4);
  $regioner = _ktc_sectionpage_filter_helper($f5);
  $gid = _ktc_sectionpage_group_filter_helper($gid);

  // If the content type:document does not included in the content_type,
  // remove the document type from term_type filter value.
  if (strpos($content_type, 'document') === FALSE) {
    if (strpos($content_type, 'all') === FALSE) {
      $term_type = _ktc_sectionpage_check_document_term($term_type);
    }
  }

  if ($page == '') {
    $page = arg(0);
  }

  // Default content_pane from view "indhold_m_filter".
  // Content displays in one columns.
  $display = 'panel_pane_4';

  if ($page == 'nyheder' || arg(0) == 'nyheder') {
    $content_type = 'os2web_base_news';
    // Content displays in two columns.
    $display = 'panel_pane_5';
  }

  if ($page == 'hoeringer' || arg(0) == 'hoeringer') {
    $content_type = 'hearing';
    // Content displays in one columns.
    $display = 'panel_pane_5';
  }
  if ($page == 'teknikmiljoe' || arg(0) == 'teknikmiljoe') {
    if ($f1 == '')
        $content_type = 'magazine';
    // Content displays in one columns.
    $display = 'panel_pane_7';
  }
  if ($page == 'netvaerk' || arg(0) == 'netvaerk') {
    // Netvaerk section includes a group type filter.
    // Get the group ids from group type(s).
    if ($gids_netvaerk_type = _ktc_sectionpage_get_gids_from_group_types($term_type)) {
      $gid = $gids_netvaerk_type;
    }
 
    // So there are no other term_type filters,
    // set value to all to exclude context filter in view.
    $term_type = 'all';
    // Content displays in two columns.
    $display = 'panel_pane_5';
  }

  // Excluede profile subpage user/group/new_content.
  if ($page != 'new_content') {
    $view = views_get_view('indhold_m_filter');

    $view->set_display($display);
    $view->set_arguments(
            array($content_type, $term_type, $emner, $tags, $regioner, $gid)
          );
    $view->pre_execute();
    $view->execute();
    return $view->render($display);
  }
  // Profile subpage user/group/new_content.
  // Get new (unreaded/updated) content from user's groups.
  else {
    if ($gid == 'all') {
      $ids = og_get_groups_by_user();
      if (!empty($ids)) {
        $ids = $ids['node'];
        $gid = implode('+', array_keys($ids));
      }
    }
    $view = views_get_view('new_content_from_group');

    $view->set_display('panel_pane_1');
    $view->set_arguments(array($gid, $content_type));
    $view->pre_execute();
    $view->execute();
    return $view->render('panel_pane_1');
  }

}

/**
 * User comments block_view call back.
 */
function _ktc_user_comments_content($page = TRUE) {
  global $user;
  // Profile subpage user/user_comments.
  // Get contents with comments from user's contents,
  // comments, and subscripted contents.
  $ids = _ktc_sectionpage_get_user_related_node_id($user->uid);

  $view = views_get_view('comments');
  if ($page) {
    $display = 'panel_pane_1';
  }
  else {
    $display = 'block_1';
  }

  $view->set_display($display);
  $view->set_arguments(array($ids));
  $view->pre_execute();
  $view->execute();
  return $view->render($display);
}


/**
 * Netvaerk content type filtre block callback.
 */
function _ktc_section_block_netvaerk_content_types() {
  $nid = arg(1);
  $types = array(); 
  $html = '<div class="filter-box">';
  if (is_numeric($nid)) {
    // Se function ktc_netvaerk_get_group_content_types in ktc_netvaerk.module.
    $types = ktc_netvaerk_get_group_content_types($nid);
  }
  elseif (arg(0) == 'netvaerk' ) {
    $types = ktc_netvaerk_get_group_content_types('all');
  }
  elseif (arg(0) == 'teknikmiljoe'){
      $types = array ('magazine', 'artikler', 'os2web_base_news' );
  }

  if (!empty($types)) {
    $html .= '<div class="ktc-filter-button-container">
      <div class="btn btn-default filter-link" id="filter-all" data-filter="all">Alle</div>
      </div>';
    foreach ($types as $type) {
      $html .= '<div class="ktc-filter-button-container">
        <div class="btn btn-default filter-link" id="' . $type . '"
        data-filter="' . $type . '" name="filter-content-type">' . node_type_get_name($type) . '</div>
      </div>';
    }
  }
  $html .= '</div>';
  return $html;
}

/**
 * Page menu local tabs callback.
 */
function _ktc_section_block_page_menu_tabs() {
  $menu = '';
  if (arg(1) == 'node' && arg(3) == 'admin' && arg(4) == 'people') {
    $nid = arg(2);
    if (is_numeric($nid)) {
      $group_menu = '<div class="filter-box">';

      $group_menu .= '<div class="ktc-filter-button-container">';
      $group_menu .= '<div class="btn btn-default filter-link">';
      $group_menu .= l('Vis', 'node/' . $nid);
      $group_menu .= '</div></div>';

      if (drupal_valid_path('node/' . $nid . '/edit')) {
        $group_menu .= '<div class="ktc-filter-button-container">';
        $group_menu .= '<div class="btn btn-default filter-link">';
        $group_menu .= l('Redigér', 'node/' . $nid . '/edit');
        $group_menu .= '</div></div>';
      }

      if (drupal_valid_path('node/' . $nid . '/group')) {
        $group_menu .= '<div class="ktc-filter-button-container">';
        $group_menu .= '<div class="btn btn-primary filter-link">';
        $group_menu .= l('Gruppe', 'node/' . $nid . '/group');
        $group_menu .= '</div></div>';
      }

      $group_menu .= '</div>';
      $menu .= $group_menu;
    }
  }

  $menu .= render(menu_local_tabs());
  return $menu;
}
/**
 * Implements hook_node_presave().
 */
function ktc_sectionpage_node_presave($node) {
  if (isset($node->modified)) {
    $node->changed = $node->modified;
  }
}
/****************** End of blocks. *******************************/

/****************** ktc_sectionpage.module helper functions. *****/

/**
 * Helper function: Filter helper.
 */
function _ktc_sectionpage_filter_helper($filter) {
  $filter_value = '';
  $filter_ar = explode(',', $filter);
  $is_term = TRUE;

  // Default filer value = all.
  if (count($filter_ar) < 1) {
    return $filter_value = 'all';
  }

  foreach ($filter_ar as $value) {
    if (!is_numeric($value)) {
      $is_term = FALSE;
    }
    if ($value == 'all' || $value == '') {
      continue;
    }

    if ($filter_value == '') {
      $filter_value = $value;
    }
    else {
      $filter_value .= '+' . $value;
    }
  }

  // Default filer value = all.
  if ($filter_value == '') {
    $filter_value = 'all';
  }

  // Default content_type value.
  if (!$is_term && $filter_value == '') {
    $filter_value = 'os2web_base_news+document+hearing+forum_post+arrangement+meeting_doodle';
  }
  return $filter_value;
}
/**
 * Remove document type (term) from the term_type.
 */
function _ktc_sectionpage_check_document_term($term_type) {
  if ($term_type == 'all') {
    return $term_type;
  }
  $filter_ar = explode('+', $term_type);
  foreach ($filter_ar as $tid) {
    $term = taxonomy_term_load($tid);
    if ($term->vocabulary_machine_name == 'dokument') {
      $filter_ar = array_pop($filter_ar);
    }
  }
  $term_type = implode('+', $filter_ar);
  if (!$term_type) {
    $term_type = 'all';
  }
  return $term_type;
}
/**
 * Helper function: Group filter helper.
 */
function _ktc_sectionpage_group_filter_helper($gid) {
  $filter_value = '';

  if ($gid == 'all,') {
    return $filter_value = 'all';
  }
  if ($gid == 'my,') {
    // Get user's group IDs.
    $ids = og_get_groups_by_user();
    if (!empty($ids)) {
      $ids = $ids['node'];
      $filter_value = implode('+', array_keys($ids));
    }
    return $filter_value;
  }

  $filter_ar = explode(',', $gid);
  foreach ($filter_ar as $value) {
    if ($value == '') {
      continue;
    }
    if (is_numeric($value)) {
      if ($filter_value == '') {
        $filter_value = $value;
      }
      else {
        $filter_value .= '+' . $value;
      }
    }
  }
  if ($filter_value == '') {
    $filter_value = 'all';
  }
  return $filter_value;
}
/**
 * Get gids from group types.
 */
function _ktc_sectionpage_get_gids_from_group_types($term_type) {
  $gids_ar = array();
  $gids = FALSE;
  if ($term_type == 'all') {
    return FALSE;
  }

  $tids = explode('+', $term_type);

  if (!empty($tids)) {
    foreach ($tids as $tid) {
      $query = db_select('field_data_field_netvaerkstype', 'n')
        ->fields('n', array('entity_id'))
        ->condition('field_netvaerkstype_tid', $tid, '=')
        ->condition('bundle', 'group', '=');
      $result = $query->execute();
      if ($result->rowCount() > 0) {
        while ($record = $result->fetchAssoc()) {
          $gids_ar[] = $record['entity_id'];
        }
      }
    }
  }

  if (!empty($gids_ar)) {
    $gids = implode('+', $gids_ar);
  }
  return $gids;
}
/**
 * Get node ids that related to a user.
 */
function _ktc_sectionpage_get_user_related_node_id($uid) {
  $id = '';
  $ids = array();
  /*$query = 'SELECT n.nid FROM {node} n,{comment} c WHERE n.uid = :uid AND n.nid = c.nid
              UNION SELECT c2.nid FROM {comment} c2 WHERE c2.uid = :uid
              UNION SELECT cast(s.value as UNSIGNED) AS nid FROM subscriptions s
              WHERE s.field = :nid AND s.recipient_uid = :uid';*/
  $query = 'SELECT n.nid FROM {node} n,{comment} c WHERE n.uid = :uid AND n.nid = c.nid
              UNION SELECT c2.nid FROM {comment} c2 WHERE c2.uid = :uid';
  $result = db_query($query, array('uid' => $uid, 'nid' => 'nid'))->fetchAll();
  if ($result) {
    foreach ($result as $node) {
      $ids[] = $node->nid;
    }
    $id = implode('+', $ids);
  }
  return $id;
}

/**
 * Group hearing nodes by years.
 */
function _ktc_sectionpage_get_hearing_years() {
  $nodes = node_load_multiple(array(), array('type' => 'hearing'));
  $years = array();
  $nids = array();
  foreach ($nodes as $node) {
    if ($date = field_get_items('node', $node, 'field_enrollment_deadlines')) {
      $year = date('Y', strtotime($date[0]['value']));
      if ($year == '1970') {
        continue;
      }
      $nids[$year][] = $node->nid;
    }
  }
  foreach ($nids as $key => $items) {

    $years[$key] = implode('+', $items);
  }

  ksort($years);

  return $years;
}


/**
 * Group hearing nodes by years.
 */
function _ktc_sectionpage_get_magazine_years() {
  $nodes = node_load_multiple(array(), array('type' => 'magazine'));
  $years = array();
  $nids = array();
  foreach ($nodes as $node) {
    if ($date = field_get_items('node', $node, 'field_udgivelsesdato')) {
      $year = date('Y', strtotime($date[0]['value']));
      if ($year == '1970') {
        continue;
      }
      $nids[$year][] = $node->nid;
    }
  }
  foreach ($nids as $key => $items) {

    $years[$key] = $items;// = implode('+', $items);
  }

  ksort($years);

  return $years;
}

/**
 * Group hearing nodes by years.
 */
function _ktc_sectionpage_get_magazine_month() {
  $nodes = node_load_multiple(array(), array('type' => 'magazine'));
  $month = array();
  $nids = array();
  foreach ($nodes as $node) {
    if ($date = field_get_items('node', $node, 'field_udgivelsesdato')) {
      $month = date('n', strtotime($date[0]['value']));
     
      $nids[$month][] = $node->nid;
     
    }
  }    
  foreach ($nids as $key => $items) {
    $monthName = date('F', mktime(0, 0, 0, $key, 10)); // March
    $months[$monthName] = $items;
  }

  

  return $months;
}

/**
 * Helper function: Get nids for view context filter by years-nids array.
 */
function _ktc_sectionpage_years_filter_helper($f5) {
  $filter_value = '';

  if ($f5 == 'all,') {
    return $filter_value = 'all';
  }
  $years = _ktc_sectionpage_get_hearing_years();
  $filter_ar = explode(',', $f5);
  foreach ($filter_ar as $value) {
    if ($value == '') {
      continue;
    }
    if (is_numeric($value)) {
      if ($filter_value == '') {
        $filter_value = $years[$value];
      }
      else {
        $filter_value .= '+' . $years[$value];
      }
    }
  }
  if ($filter_value == '') {
    $filter_value = 'all';
  }
  return $filter_value;
}
/**
 * Helper function: Get nids for view context filter by years-nids array.
 */
function _ktc_sectionpage_magazine_years_filter_helper($f3, $f4) {
  $year_filter_value = array();
  $month_filter_value = array();
  $filter_value = '';
  if ($f3 == 'all' and $f4== 'all') {
    return $filter_value = 'all';
  }
   if ($f3 == '' and $f4== '') {
    return $filter_value = 'all';
  }
  
  $years = _ktc_sectionpage_get_magazine_years();
  $filter_ar = explode(',', $f3);
  foreach ($filter_ar as $value) {
    if ($value == '') {
      continue;
    }
    if (is_numeric($value)) {
      //if ($filter_value == '') {
        foreach ($years[$value] as $key =>$nid)
            $year_filter_value[] = $nid;
     
      //}
     // else {
     //   $filter_value .= '+' . $years[$value];
     // }
    }
  }
  
  
   $months = _ktc_sectionpage_get_magazine_month();
  $filter_ar = explode(',', $f4);

  foreach ($filter_ar as $value) {
    if ($value == '') {
      continue;
    }   
      //if ($filter_value == '') {
    foreach ($months[$value] as $key =>$nid)
        $month_filter_value[] = $nid;
      //}
     // else {
       // $filter_value .= '+' . $months[$value];
      //}
    }
    if (!empty($month_filter_value) && !empty($year_filter_value)){
        $filter_value = implode('+',  array_intersect($year_filter_value, $month_filter_value));
        
    }
    elseif(empty($month_filter_value)) {
        $filter_value = implode('+',  $year_filter_value);
    }
    else {
        $filter_value = implode('+',  $month_filter_value);
    }
  
 /* if ($filter_value == '') {
    $filter_value = 'all';
  }*/
  return $filter_value;
}

function _ktc_sectionpage_helper_get_term_depth($parent_id){
    $terms = explode(',', $parent_id);
    $tid = array_shift($terms);
    $parent = db_query("SELECT parent FROM {taxonomy_term_hierarchy} WHERE tid = :tid", array(':tid' => $tid))->fetchField();
    if($parent == 0) {
        return 1;
    }else  {
        return 1+_ktc_sectionpage_helper_get_term_depth($parent);
  }
   
}
