<?php
/**
 * @file
 * Code for the KTC users feature.
 */

include_once 'ktc_users.features.inc';

/**
 * Get users data.
 */
function ktc_users_get_user_info($user, $info_type) {
  $info_type = ucfirst($info_type);
  $info = array();

  switch ($info_type) {
    case 'Work':
      $field = field_get_items('user', $user, 'field_account');
      if ($field and $account = taxonomy_term_load($field[0]['tid'])) {
        $info = ktc_users_get_user_info_work_data($account);
      }
      else {
        $info = ktc_users_get_user_info_old_work_data($user);
      }
      break;

    case 'Personal':
      $info = ktc_users_get_user_info_personal_data($user);
      break;
  }
  return $info;
}

/**
 * Return users personal data.
 */
function ktc_users_get_user_info_personal_data($entity) {
  $data = array();

  // User ID.
  if ($entity->uid) {
    $data['uid'] = $entity->uid;
  }
  // Job title.
  if ($field = field_get_items('user', $entity, 'field_jobposition')) {
    $data['job_title'] = $field[0]['value'];
  }
  // Email.
  if ($entity->mail) {
    $data['email'] = $entity->mail;
  }
  // LinkedIn.
  if ($field = field_get_items('user', $entity, 'field_linkedin')) {
    $data['linked_in'] = $field[0]['value'];
  }
  // Twitter.
  if ($field = field_get_items('user', $entity, 'field_twitter_brugernavn')) {
    $data['twitter'] = $field[0]['value'];
  }
  // Direct phone.
  if ($field = field_get_items('user', $entity, 'field_directe_telefon')) {
    $data['direct_phone'] = $field[0]['value'];
  }
  // Cellphone.
  if ($field = field_get_items('user', $entity, 'field_cell')) {
    $data['cellphone'] = $field[0]['value'];
  }
  // Firstname.
  if ($field = field_get_items('user', $entity, 'field_navn')) {
    $data['firstname'] = $field[0]['value'];
  }
  // Lastname.
  if ($field = field_get_items('user', $entity, 'field_efternavn')) {
    $data['lastname'] = $field[0]['value'];
  }
  // Full name.
  if (isset($data['firstname']) || isset($data['lastname'])) {
    if (isset($data['firstname']) && ! isset($data['lastname'])) {
      $data['full_name'] = $data['firstname'];
    }
    elseif ( ! isset($data['firstname']) && isset($data['lastname'])) {
      $data['full_name'] = $data['lastname'];
    }
    else {
      $data['full_name'] = $data['firstname'] . ' ' . $data['lastname'];
    }
  }
  // Address.
  if ($field = field_get_items('user', $entity, 'field_adresse')) {
    $data['address'] = $field[0]['value'];
  }
  // Address 2.
  if ($field = field_get_items('user', $entity, 'field_adresse_2')) {
    $data['address_2'] = $field[0]['value'];
  }
  // Zipcode.
  if ($field = field_get_items('user', $entity, 'field_zipcode')) {
    $data['zipcode'] = $field[0]['value'];
  }
  // City.
  if ($field = field_get_items('user', $entity, 'field_city')) {
    $data['city'] = $field[0]['value'];
  }
  // Country.
  if ($field = field_get_items('user', $entity, 'field_country')) {
    $data['country'] = $field[0]['value'];
  }
  // Education.
  if ($field = field_get_items('user', $entity, 'field_uddannelser_og_kurser')) {
    $data['education'] = $field[0]['value'];
  }
  // Special skills.
  if ($field = field_get_items('user', $entity, 'field_special_skills')) {
    $data['special_skills'] = $field[0]['value'];
  }

  return $data;
}

/**
 * Return legacy data for work place.
 *
 * This is only relevant while the user has not updated his/her userprofile
 * to reference a company taxonomy
 */
function ktc_users_get_user_info_old_work_data($entity) {
  $data = array();

  if ($field = field_get_items('user', $entity, 'field_employer_name')) {
    $data['company'] = $field[0]['value'];
  }
  if ($field = field_get_items('user', $entity, 'field_department')) {
    $data['department'] = $field[0]['value'];
  }
  // Phone.
  if ($field = field_get_items('user', $entity, 'field_phone')) {
    $data['phone'] = $field[0]['value'];
  }
  // EAN number.
  if ($field = field_get_items('user', $entity, 'field_ean')) {
    $data['ean_number'] = $field[0]['value'];
  }
  // VAT number.
  if ($field = field_get_items('user', $entity, 'field_cvr')) {
    $data['vat_number'] = $field[0]['value'];
  }
  // Address.
  if ($field = field_get_items('user', $entity, 'field_adresse')) {
    $data['address'] = $field[0]['value'];
  }
  // Address 2.
  if ($field = field_get_items('user', $entity, 'field_adresse_2')) {
    $data['address_2'] = $field[0]['value'];
  }
  // Zipcode.
  if ($field = field_get_items('user', $entity, 'field_zipcode')) {
    $data['zipcode'] = $field[0]['value'];
  }
  // City.
  if ($field = field_get_items('user', $entity, 'field_city')) {
    $data['city'] = $field[0]['value'];
  }
  // Country.
  if ($field = field_get_items('user', $entity, 'field_country')) {
    $data['country'] = $field[0]['value'];
  }

  return $data;
}

/**
 * Return data about users work place.
 */
function ktc_users_get_user_info_work_data($entity) {
  $data = array();
  $parents = taxonomy_get_parents_all($entity->tid);

  // Company.
  if ($entity->name) {
    $index = count($parents) - 2;

    if ($index < 0) {
      $index = 0;
    }
    
    $data['company'] = $parents[$index]->name;
  }
  // Department
  $data['department'] = $entity->name;
  // Phone.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_phone')) {
    $data['phone'] = $field[0]['value'];
  }
  // EAN number.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_ean')) {
    $data['ean_number'] = $field[0]['value'];
  }
  // VAT number.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_cvr')) {
    $data['vat_number'] = $field[0]['value'];
  }
  // Address.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_adresse')) {
    $data['address'] = $field[0]['value'];
  }
  // Address 2.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_adresse_2')) {
    $data['address_2'] = $field[0]['value'];
  }
  // Zipcode.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_zipcode')) {
    $data['zipcode'] = $field[0]['value'];
  }
  // City.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_city')) {
    $data['city'] = $field[0]['value'];
  }
  // Country.
  if ($field = field_get_items('taxonomy_term', $entity, 'field_country')) {
    $data['country'] = $field[0]['value'];
  }

  return $data;
}

/**
 * Return the users address. in specified format.
 */
function ktc_users_get_user_address($user, $type, $data_format = 'html') {
  $type = ucfirst($type);

  // HTML.
  if ($data_format == 'html') {
    switch ($type) {
      case 'Work':
        if ($field = field_get_items('user', $user, 'field_account')) {
          if ($account = taxonomy_term_load($field[0]['tid'])) {
            $data = ktc_users_get_formatted_address($account, 'taxonomy_term', $data_format);
          }
        }
        break;

      case 'Private':
        $data = ktc_users_get_formatted_address($user, 'user', $data_format);
        break;
    }
  }

  // Data. 
  elseif ($data_format == 'data') {
    switch ($type) {
      case 'Work':
        if ($field = field_get_items('user', $user, 'field_account')) {
          if ($account = taxonomy_term_load($field[0]['tid'])) {
            $data = ktc_users_get_formatted_address($account, 'taxonomy_term', $data_format);
          }
        }
        break;

      case 'Private':
        $data = ktc_users_get_formatted_address($user, 'user', $data_format);
        break;
    }
  }

  return $data;
}

/**
 * Return formatted address for entity (user/taxonomy {account}).
 */
function ktc_users_get_formatted_address($entity, $type, $data_format = 'html') {
  $html = '';
  $data = array();

  if ($field = field_get_items($type, $entity, 'field_adresse')) {
    $html = $field[0]['value'] . '<br />';
    $data['address'] = $field[0]['value'];
  }
  if ($field = field_get_items($type, $entity, 'field_adresse_2')) {
    $html .= $field[0]['value'] . '<br />';
    $data['address_2'] = $field[0]['value'];
  }
  if ($field = field_get_items($type, $entity, 'field_zipcode')) {
    $html .= $field[0]['value'] . ' ';
    $data['zipcode'] = $field[0]['value'];
  }
  if ($field = field_get_items($type, $entity, 'field_city')) {
    $html .= $field[0]['value'] . '<br />';
    $data['city'] = $field[0]['value'];
  }
  if ($field = field_get_items($type, $entity, 'field_country')) {
    $html .= $field[0]['value'];
    $data['country'] = $field[0]['value'];
  }

  // Return value.
  if ($data_format == 'html') {
    $return = $html;
  }
  elseif ($data_format == 'data') {
    $return = $data;
  }

  return $return;
}


/**
 * Implements hook_entity_info_alter().
 *
 * The first attribute in the array defines an arbitrary label for the view mode machine name.
 * 'custom settings' => TRUE displays the view mode as a default at the top of the display modes settings screen
 */
function ktc_users_entity_info_alter(&$entity_info) {
  $entity_info['user']['view modes']['teaser'] = array(
    'label' => t('User teaser'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['teaser2'] = array(
    'label' => t('User teaser 2'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list1'] = array(
    'label' => t('User List 1'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list2'] = array(
    'label' => t('User List 2'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list3'] = array(
    'label' => t('User List 3'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list4'] = array(
    'label' => t('User List 4'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list5'] = array(
    'label' => t('User List 5'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list6'] = array(
    'label' => t('User List 6'),
    'custom settings' => TRUE,
  );
  $entity_info['user']['view modes']['list7'] = array(
    'label' => t('User List 7'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_alter().
 */
function ktc_users_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_block') {
    $form['#validate'][] = 'ktc_users_verify_email';
  }

  // Hide hidden form field_group.
  if ($form_id == 'user_profile_form') {
    ktc_users_field_group_hide_field_groups($form, array('group_hidden'));
  }
}

/**
 * Stop users first login, if not from email.
 */
function ktc_users_verify_email($form, $form_state) {
  if ($form_state['uid']) {
    $account = user_load($form_state['uid']);

    if (!$account->access) {
      form_set_error('name', t('Du skal først verificere din e-mail adresse. Tryk <a href="@link">her</a> for at få tilsendt en ny mail.', array('@link' => '/user/password')));
    }
  }
}

/**
 * Implements hook_user_presave().
 */
function ktc_users_user_presave(&$edit, $account, $category) {
  // Only update user if $_POST['form_id'] is correct. Presave is also called
  // when a user is updated programmatically, so this could turn into an
  // unwanted loop otherwise.
  if (isset($_POST['form_id']) && ($_POST['form_id'] == 'user_profile_form' || $_POST['form_id'] == 'ktc_users_signup_form')) {
    $tmp_account = clone $account;
    foreach ($edit as $key => $value) {
      $tmp_account->$key = $value;
    }

    if ($field = field_get_items('user', $tmp_account, 'field_navn')) {
      $name = trim($field[0]['value']);
    }

    if ($field = field_get_items('user', $tmp_account, 'field_efternavn')) {
      $name .= ' ' . trim($field[0]['value']);
    }

    if ($field = field_get_items('user', $tmp_account, 'field_account')) {
      $term = taxonomy_term_load($field[0]['tid']);

      $fetch_parent = TRUE;

      while ($fetch_parent) {
        $field = field_get_items('taxonomy_term', $term, 'field_toplevelaccountname');
        if (!$field[0]['value']) {
          $employer = $term->name;
          $fetch_parent = FALSE;
        }
        $term = reset(taxonomy_get_parents($term->tid));

        if (!$term) {
          $fetch_parent = FALSE;
        }
      }
    }

    $username = ktc_users_generate_username($name, $employer, $email, $tmp_account->uid);

    $edit['name'] = $username;
  }
}

/**
 * Hides field groups including children in a render array.
 *
 * @param array $element
 *   A render array. Can be a form, node, user, ...
 * @param array $group_names
 *   An array of field group names that should be hidden.
 */
function ktc_users_field_group_hide_field_groups(&$element, $group_names) {
  foreach ($group_names as $group_name) {
    if (isset($element['#fieldgroups'][$group_name]) && isset($element['#group_children'])) {
      // Hide the field group.
      $element['#fieldgroups'][$group_name]->format_type = 'hidden';
      // Hide the elements inside the field group.
      foreach (array_keys($element['#group_children'], $group_name) as $field_name) {
        $element[$field_name]['#access'] = FALSE;
      }
    }
  }
}

/**
 * Generate a pretty username for the user.
 */
function ktc_users_generate_username($name, $employer, $email, $uid) {
  // If name is empty, use the email. This is only a temporary solution
  // until the user edits his userprofile the first time.
  $name = trim($name);
  if (!$name) {
    $name = $email;
  }

  // The actual username. We replace some of the illegal username characters.
  $username = trim($name);

  if ($employer) {
    $username .= ' - ' . trim($employer);
  }

  $username = str_replace(array(',', '/', '+'), array('', '-', ''), $username);

  // Drupal only allows the users to have a 60 character long username.
  if (strlen($username) > 60) {
    if (strlen($name) > 28) {
      $name = substr($name, 0, 26) . '..';
    }

    if (strlen($employer) > 28) {
      $employer = substr($employer, 0, 26) . '..';
    }
    return ktc_users_generate_username($name, $employer, $email, $uid);
  }

  // Check just to be sure, that the username is not already taken.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'user')
    ->propertyCondition('name', $username)
    ->propertyCondition('uid', $uid, '!=');
  $result = $query->execute();

  if (isset($result['user'])) {
    // This is a non-solution. We append a "." to the employername if the
    // username is already taken. This should only happen due to old incorrect
    // data.
    return ktc_users_generate_username($name, $employer . '.', $email, $uid);
  }

  return $username;
}

/**
 * Get users grouprole depeding on the current group context.
 */
function ktc_users_get_user_network_role($account) {
  $node = menu_get_object('node');
  $gid = FALSE;

  if (!$node) {
    return FALSE;
  }

  if ($node->type == 'group') {
    $gid = $node->nid;
  }

  if ($field = field_get_items('node', $node, 'field_vis_netvaerk')) {
    $gid = $field[0]['target_id'];
  }

  if (!$gid) {
    return FALSE;
  }

  if ($membership = og_get_membership('node', $gid, 'user', $account->uid)) {
    if ($field = field_get_items('og_membership', $membership, 'field_grouprole')) {
      $group_role = taxonomy_term_load($field[0]['target_id']);
      return $group_role->name;
    }
  }

  return 'Medlem';
}
