<?php
/**
 * @file
 * Code for the KTC users feature.
 */

include_once 'ktc_users.features.inc';

/**
 * Implements hook_entity_info_alter().
 *
 * The first attribute in the array defines an arbitrary label for the view mode machine name.
 * 'custom settings' => TRUE displays the view mode as a default at the top of the display modes settings screen
 */
function ktc_users_entity_info_alter(&$entity_info) {
  $entity_info['user']['view modes']['teaser'] = array(
    'label' => t('User teaser'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['teaser2'] = array(
    'label' => t('User teaser 2'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list1'] = array(
    'label' => t('User List 1'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list2'] = array(
    'label' => t('User List 2'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list3'] = array(
    'label' => t('User List 3'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list4'] = array(
    'label' => t('User List 4'),
    'custom settings' => TRUE,
  );
    $entity_info['user']['view modes']['list5'] = array(
    'label' => t('User List 5'),
    'custom settings' => TRUE,
  );

}

function ktc_users_preprocess_user_profile(&$vars) {
  if ($vars['elements']['#view_mode'] == 'teaser2') {
    $vars['theme_hook_suggestions'][] = 'user_profile__teaser2';
  }
  if ($vars['elements']['#view_mode'] == 'list1') {
    $vars['theme_hook_suggestions'][] = 'user_profile__list1';
  }
  if ($vars['elements']['#view_mode'] == 'list2') {
    $vars['theme_hook_suggestions'][] = 'user_profile__list2';
  }
  if ($vars['elements']['#view_mode'] == 'list3') {
    $vars['theme_hook_suggestions'][] = 'user_profile__list3';
  }
  if ($vars['elements']['#view_mode'] == 'list4') {
    $vars['theme_hook_suggestions'][] = 'user_profile__list4';
  }
  if ($vars['elements']['#view_mode'] == 'list5') {
    $vars['theme_hook_suggestions'][] = 'user_profile__list5';
  }
}

/**
 * Implements hook_form_alter().
 */
function ktc_users_form_alter(&$form, &$form_state, $form_id) {
  // Hide hidden form field_group.
  if ($form_id == 'user_profile_form') {
    ktc_users_field_group_hide_field_groups($form, array('group_hidden'));
  }
}

/**
 * Implements hook_user_presave().
 */
function ktc_users_user_presave(&$edit, $account, $category) {
  // Only update user if $_POST['form_id'] is correct. Presave is also called
  // when a user is updated programmatically, so this could turn into an
  // unwanted loop otherwise.
  if (isset($_POST['form_id']) && ($_POST['form_id'] == 'user_profile_form' || $_POST['form_id'] == 'ktc_users_signup_form')) {
    $tmp_account = clone $account;
    foreach ($edit as $key => $value) {
      $tmp_account->$key = $value;
    }

    if ($field = field_get_items('user', $tmp_account, 'field_navn')) {
      $name = trim($field[0]['value']);
    }

    if ($field = field_get_items('user', $tmp_account, 'field_efternavn')) {
      $name .= ' ' . trim($field[0]['value']);
    }

    if ($field = field_get_items('user', $tmp_account, 'field_account')) {
      $term = taxonomy_term_load($field[0]['tid']);
      $employer = $term->name;
    }

    $username = ktc_users_generate_username($name, $employer, $email, $tmp_account->uid);

    $edit['name'] = $username;
  }
}

/**
 * Hides field groups including children in a render array.
 *
 * @param array $element
 *   A render array. Can be a form, node, user, ...
 * @param array $group_names
 *   An array of field group names that should be hidden.
 */
function ktc_users_field_group_hide_field_groups(&$element, $group_names) {
  foreach ($group_names as $group_name) {
    if (isset($element['#fieldgroups'][$group_name]) && isset($element['#group_children'])) {
      // Hide the field group.
      $element['#fieldgroups'][$group_name]->format_type = 'hidden';
      // Hide the elements inside the field group.
      foreach (array_keys($element['#group_children'], $group_name) as $field_name) {
        $element[$field_name]['#access'] = FALSE;
      }
    }
  }
}

/**
 * Generate a pretty username for the user.
 */
function ktc_users_generate_username($name, $employer, $email, $uid) {
  // If name is empty, use the email. This is only a temporary solution
  // until the user edits his userprofile the first time.
  if (!$name) {
    $name = $email;
  }

  // The actual username. We replace some of the illegal username characters.
  $username = trim($name);

  if ($employer) {
    $username .= ' - ' . trim($employer);
  }

  $username = str_replace(array(',', '/', '+'), array('', '-', ''), $username);

  // Drupal only allows the users to have a 60 character long username.
  if (strlen($username) > 60) {
    if (strlen($name) > 27) {
      $name = substr($name, 0, 27) . '..';
    }

    if (strlen($employer) > 27) {
      $employer = substr($employer, 0, 27) . '..';
    }
    return ktc_users_generate_username($name, $employer, $email, $uid);
  }

  // Check just to be sure, that the username is not already taken.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'user')
    ->propertyCondition('name', $username)
    ->propertyCondition('uid', $uid, '!=');
  $result = $query->execute();

  if (isset($result['user'])) {
    // This is a non-solution. We append a "." to the employername if the
    // username is already taken. This should only happen due to old incorrect
    // data.
    return ktc_users_generate_username($name, $employer . '.', $email, $uid);
  }

  return $username;
}
