<?php
/**
 * @file
 * Code for the KTC Subscriptions UI feature.
 */

include_once 'ktc_subscription_ui.features.inc';
/**
 * @file
 * KTC Subscription UI module.
 */

/**
 * Implements hook_menu().
 */
function ktc_subscription_ui_menu() {
  $items['admin/ktc/subscription'] = array(
    'title' => 'Abonnementer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_admin_form'),
    'access arguments' => array('administer site'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user/%user/abonnementer'] = array(
    'title' => 'Mine abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(1),
    'page callback' => 'ktc_subscription_ui_page',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/abonnementer/%/edit'] = array(
    'title' => 'Mine abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/abonnementer/%/add'] = array(
    'title' => 'Mine abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/abonnementer/%/cancel'] = array(
    'title' => 'Mine abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_crm_subscription_cancel_form', 1, 3),
  );

  $items['abonnementer'] = array(
    'access callback' => TRUE,
    'page callback' => 'ktc_subscription_ui_redirect',
  );

  $items['user/%user/medlemskab'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter KTC medlemskab',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(1),
    'page callback' => 'ktc_subscription_ui_page',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/medlemskab/%/edit'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter medlemskab',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/medlemskab/%/add'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter medlemskab',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/medlemskab/%/cancel'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter medlemskab',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_crm_subscription_cancel_form', 1, 3),
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ktc_subscription_ui_theme() {
  return array(
    'ktc_subscription_ui_page' => array(
      'template' => 'ktc-crm-subscriptions-page',
    ),
  );
}

/**
 * Redirect to current users subscription for specified product.
 */
function ktc_subscription_ui_redirect($product_id = '') {
  global $user;

  // If the user is logged in, redirect to the subscription page.
  if ($user->uid) {
    drupal_goto("user/$user->uid/abonnementer/$product_id");
  }
  else {
    drupal_set_message('Du skal logge ind for at kunne se dine abonnementer');
    drupal_goto('user/login', array('query' => array('destination' => "abonnementer/$product_id")));
  }
}

/**
 * Page callback, user subscriptions overview.
 */
function ktc_subscription_ui_page($account) {
  $args = array();

  $type = 'subscription';
  if (arg(2) == 'medlemskab') {
    $type = 'ktc_membership';
  }

  $args['subscription_nodes'] = ktc_subscription_ui_get_product_list($type);
  $args['user_subscriptions'] = ktc_crm_subscriptions_fetch_user_subscriptions($account);

  return theme('ktc_subscription_ui_page', $args);
}

/**
 * Form callback for creating/editing a subscription.
 */
function ktc_subscription_ui_form($form, &$form_state, $account, $product_nid) {
  $css = '
      .container-inline-date {clear: none; float: left;}
      #edit-invoiceaccount-hierarchical-select-selects-0 {display: none;}
      #edit-invoiceaccount-hierarchical-select-selects-1 option:first-child {display: none;}
      #edit-submit {display: block; clear: left; margin-top: 10px; float: left; margin-top: 10px;}
    ';
  drupal_add_css($css, 'inline');

  $form = array();

  if ($product = node_load($product_nid)) {
    if ($field = field_get_items('node', $product, 'field_product_type')) {
      $ktc_membership = ($field[0]['value'] == 'ktc_membership');
      $form_state['ktc_membership'] = $ktc_membership;
    }

    $form['text'] = array(
      '#type' => 'item',
      '#markup' => render(field_view_field('node', $product, 'body', array('label' => 'hidden'))),
    );

    if ($product_uuid = _ktc_crm_get_uuid('node', $product)) {
      $user_uuid = _ktc_crm_get_uuid('user', $account);

      $subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);
      if (isset($subscriptions[$product_uuid])) {
        $form_state['subscriptiondto'] = $subscriptions[$product_uuid];
        $is_new = FALSE;
      }
      else {
        $form_state['subscriptiondto'] = new \KTC\Subscription\SubscriptionDto(NULL);
        $form_state['subscriptiondto']->ProductId = $product_uuid;
        $form_state['subscriptiondto']->RecipientId = $user_uuid;
        $form_state['subscriptiondto']->Abonnementsansvarlig = $user_uuid;
        $form_state['subscriptiondto']->KundensReference = $account->name;
        $form_state['subscriptiondto']->OtherAddress = new \KTC\Subscription\AddressDto();
        $is_new = TRUE;
      }

      $vocab = taxonomy_vocabulary_machine_name_load('accounts');
      $invoiceaccount = ktc_crm_account_load_from_uuid($form_state['subscriptiondto']->InvoiceAccountId);

      if (!$invoiceaccount) {
        $invoiceaccount = _ktc_crm_account_get_users_account($account);
      }

      if ($field = field_get_items('node', $product, 'field_text_before_invoiceaccount')) {
        $form['text_before_invoiceaccount'] = array(
          '#markup' => '<div>' . $field[0]['value'] . '</div><br />',
        );
      }

      $form['invoiceaccount'] = array(
        '#type' => 'hierarchical_select',
        '#title' => t('Firma'),
        '#required' => TRUE,
        '#config' => array(
          'module' => 'hs_taxonomy',
          'params' => array(
            'vid' => $vocab->vid,
          ),
          'require_entity' => 0,
          'render_flat_select' => 0,
          'save_lineage' => 0,
          'entity_count' => 0,
          'enforce_deepest' => 0,
          'editability' => array('status' => 0),
          'dropbox' => array('status' => 0),
          'level_labels' => array('status' => 0),
        ),
        '#default_value' => $invoiceaccount->tid,
      );

      $form['ean'] = array(
        '#title' => 'EAN',
        '#type' => 'textfield',
        '#required' => TRUE,
        '#default_value' => $form_state['subscriptiondto']->EAN,
      );

      // Don't let the user change the invoice account, if this is a
      // ktc_membership.
      if ($ktc_membership) {
        $form['invoiceaccount'] = array(
          '#type' => 'value',
          '#prefix' => 'Topniveau Firmanavn<br />Firma(afdelingsnanv)<br />Adresse 1<br />Adresse 2<br />Postnr, By',
          '#value' => array($invoiceaccount->tid),
        );

        if ($top_level_account = ktc_crm_account_load_top_level_account($invoiceaccount)) {
          if ($field = field_get_items('taxonomy_term', $top_level_account, 'field_regioner')) {
            $region_tid = $field[0]['tid'];

            $ktc_membership_settings = variable_get('ktc_subscription_ktc_membership', array());

            if (isset($ktc_membership_settings['region'][$region_tid])) {
                $region_uuid = $ktc_membership_settings['region'][$region_tid]['uuid'];
                $region_name = $ktc_membership_settings['region'][$region_tid]['name'];
              }
          }

          $form['kreds'] = array(
            '#tree' => FALSE,
            '#type' => 'fieldset',
          );

          if ($field = field_get_items('node', $product, 'field_text_before_region')) {
            $form['kreds']['text_before_region'] = array(
              '#markup' => '<div>' . $field[0]['value'] . '</div><br />',
            );
          }

          $form['kreds']['region'] = array(
            '#type' => 'value',
            '#prefix' => $region_name,
            '#value' => $region_uuid,
          );
        }

        $prefix = '';

        if ($field = field_get_items('node', $product, 'field_text_before_membership')) {
          $prefix = '<div>' . $field[0]['value'] . '</div>';
        }
        $form['ktc_membership_type'] = array(
          '#tree' => FALSE,
          '#type' => 'fieldset',
        );

        $form['ktc_membership_type']['ktc_membership_type'] = array(
          '#title' => 'Vælg medlemsparagraf',
          '#type' => 'select',
          '#prefix' => $prefix,
          '#required' => TRUE,
          '#options' => array(
            '3-1A' => '§3. Stk.1A - Direktør/direktionsmedlem',
            '3-1A-sup' => '§3. Stk.1A-sup - Direktør/direktionsmedlem suppl.',
            '3-1B' => '§3. Stk.1B - Andre chefer med ref. til 1a',
            '3-1C' => '§3. Stk.1C - Direktør/øverste chef fælles kommunal selskab',
            '3-1D' => '§3. Stk.1D - Andre chefer med ref. til 1c',
            '3-1E' => '§3. Stk.1E - Direktør i 100% komm. ejet selskab',
            '3-1F' => '§3. Stk.1F - Formand associeret forening',
            '3-1G' => '§3. Stk.1G - Særlig fagkundskab eller ledende rolle',
            'senior' => 'Senior',
          ),
        );
      }

      $recipient_addresses['Work'] = array(
        'Arbejde',
        ktc_crm_get_user_address($account, 'Work'),
        l(t('ret'), 'user/' . $account->uid . '/edit', array('query' => array('destination' => current_path()))),
      );

      $recipient_addresses['Private'] = array(
        'Privat',
        ktc_crm_get_user_address($account, 'Private'),
        l(t('ret'), 'user/' . $account->uid . '/edit', array('query' => array('destination' => current_path()))),
      );

      $recipient_addresses['Other'] = array(
        'Anden leveringsadresse',
        'Udfyldes herunder.',
        '',
      );

      if ($field = field_get_items('node', $product, 'field_text_before_address')) {
        $form['text_before_address'] = array(
          '#markup' => '<div>' . $field[0]['value'] . '</div><br />',
        );
      }

      $form['recipient_address'] = array(
        '#prefix' => '<label>Vælg leveringsadresse</label>',
        '#type' => 'tableselect',
        '#multiple' => FALSE,
        '#header' => array('Leveres til', 'Adresse', ''),
        '#required' => TRUE,
        '#options' => $recipient_addresses,
        '#default_value' => $form_state['subscriptiondto']->RecipientAddress,
      );

      $text_before_address = 'Udfyldes kun, hvis "Anden leveringsadresse" vælges ovenfor.';

      if ($field = field_get_items('node', $product, 'field_text_before_other_address')) {
        $text_before_other_address = $field[0]['value'];
      }

      $form['other_address'] = array(
        '#type' => 'fieldset',
        '#title' => 'Anden leveringsadresse',
        '#description' => $text_before_other_address,
        '#tree' => FALSE,
      );

      $form['other_address']['address_line_1'] = array(
        '#title' => t('Vejnavn'),
        '#type' => 'textfield',
        '#default_value' => $form_state['subscriptiondto']->OtherAddress->AddressLine1,
      );

      $form['other_address']['address_line_2'] = array(
        '#title' => t('Vejnavn 2'),
        '#type' => 'textfield',
        '#default_value' => $form_state['subscriptiondto']->OtherAddress->AddressLine2,
      );

      $form['other_address']['postal_code'] = array(
        '#title' => t('Postnummer'),
        '#type' => 'textfield',
        '#default_value' => $form_state['subscriptiondto']->OtherAddress->PostalCode,
      );

      $form['other_address']['city'] = array(
        '#title' => t('By'),
        '#type' => 'textfield',
        '#default_value' => $form_state['subscriptiondto']->OtherAddress->City,
      );

      $form['other_address']['country'] = array(
        '#title' => t('Land'),
        '#type' => 'textfield',
        '#default_value' => $form_state['subscriptiondto']->OtherAddress->Country,
      );

      if ($field = field_get_items('node', $product, 'field_text_before_submit')) {
        $form['text_before_submit'] = array(
          '#type' => 'checkbox',
          '#title' => $field[0]['value'],
          '#required' => TRUE,
        );
      }

      // Generate default value for date_popup.
      $startdate = str_replace(array('T', 'Z'), array(' ', ''), $form_state['subscriptiondto']->StartDate);
      // If there is no startdate, assume that this is a new subscription and
      // prefill the value with 'now'.
      if (!$startdate) {
        $startdate = date('Y-m-d H:i:s', strtotime('now'));
      }
      $enddate = str_replace(array('T', 'Z'), array(' ', ''), $form_state['subscriptiondto']->EndDate);
      // Same for enddate, if none is set, generate appropriate prefill values.
      if (!$form_state['subscriptiondto']->EndDate) {
        $enddate = '';
      }

      // If the product allows showing a datepicker add that form item.
      $field = field_get_items('node', $product, 'field_show_datepicker');
      if ($field && $field[0]['value']) {
        if ($field = field_get_items('node', $product, 'field_text_before_date')) {
          $form['text_date'] = array(
            '#type' => 'item',
            '#markup' => $field[0]['value'],
          );
        }

        $form['startdate'] = array(
          '#title' => 'Startdato',
          '#type' => 'date_popup',
          '#date_format' => 'd/m/Y',
          '#date_year_range' => ':+20',
          '#default_value' => $startdate,
          '#date_label_position' => 'invisible',
        );
        $form['enddate'] = array(
          '#title' => 'Slutdato',
          '#type' => 'date_popup',
          '#date_format' => 'd/m/Y',
          '#date_year_range' => ':+20',
          '#default_value' => $enddate,
          '#date_label_position' => 'invisible',
        );
      }
      else {
        // If not, we just set the enddate to somewhere in the future.
        $form['startdate'] = array(
          '#type' => 'value',
          '#value' => $startdate,
        );

        // If no enddate is set on the subscription object, set one well into
        // the future.
        if (!$form_state['subscriptiondto']->EndDate) {
          $enddate = '';
        }

        $form['enddate'] = array(
          '#type' => 'value',
          '#value' => $enddate,
        );
      }

      $submit = $is_new ? t('Opret abonnement') : t('Gem abonnement');
      if ($ktc_membership) {
        $submit = $is_new ? t('Opret medlemskab') : t('Gem medlemskab');
      }

      $form['submit'] = array(
        '#prefix' => '<br /><br /><br />',
        '#value' => $submit,
        '#type' => 'submit',
      );
    }
  }

  return $form;
}

/**
 * Submit handler for create/update subscription form.
 */
function ktc_subscription_ui_form_submit(&$form, &$form_state) {
  $subscriptiondto = $form_state['subscriptiondto'];

  $invoiceaccount = taxonomy_term_load($form_state['values']['invoiceaccount'][0]);

  $invoiceaccountid = _ktc_crm_get_uuid('taxonomy_term', $invoiceaccount);

  $subscriptiondto->InvoiceAccountId = $invoiceaccountid;
  $subscriptiondto->EAN = $form_state['values']['ean'];
  $subscriptiondto->RecipientAddress = $form_state['values']['recipient_address'];

  $addressdto = new KTC\Subscription\AddressDto($form_state['values']['crm_uuid']);

  $addressdto->AddressLine1 = $form_state['values']['address_line_1'];
  $addressdto->AddressLine2 = $form_state['values']['address_line_2'];
  $addressdto->PostalCode = $form_state['values']['postal_code'];
  $addressdto->City = $form_state['values']['city'];
  $addressdto->Country = $form_state['values']['country'];

  $subscriptiondto->OtherAddress = $addressdto;

  $subscriptiondto->StartDate = date('Y-m-d\TH:i:s\Z', strtotime($form_state['values']['startdate']));
  // Only set enddate, if one is selected.
  if ($form_state['values']['enddate']) {
    $subscriptiondto->EndDate = date('Y-m-d\TH:i:s\Z', strtotime($form_state['values']['enddate']));
  }

  // Default redirect path.
  $overview_path = 'abonnementer';

  // If this is a ktc_membership, handle the extra products aswell.
  if ($form_state['ktc_membership']) {
    $ktc_membership_settings = variable_get('ktc_subscription_ktc_membership', array());

    $region_subscriptiondto = clone $subscriptiondto;
    $tm_subscriptiondto = clone $subscriptiondto;

    $region_subscriptiondto->ProductId = $form_state['values']['region'];
    $tm_subscriptiondto->ProductId = $ktc_membership_settings['tm_uuid'];
    ktc_crm_update_user_subscription($region_subscriptiondto);
    ktc_crm_update_user_subscription($tm_subscriptiondto);

    // Redirect to membership overview.
    $overview_path = 'medlemskab';
  }

  ktc_crm_update_user_subscription($subscriptiondto);

  global $user;
  drupal_goto('user/' . $user->uid . '/' . $overview_path);
}

/**
 * Validation handler for create/update subscription form.
 */
function ktc_subscription_ui_form_validate(&$form, &$form_state) {
  if ($form_state['values']['enddate'] && strtotime($form_state['values']['enddate']) < time()) {
    form_set_error('enddate', t('Du skal vælge en dato i fremtiden'));
  }
  if (!ktc_subscription_ui_validate_ean($form_state['values']['ean'])) {
    form_set_error('ean', t('Det indtastede EAN er ikke gyldigt.'));
  }
  if (!$form_state['values']['region']) {
    form_set_error('region', t('Kredsmedlemsskabet kunne ikke bestemmes, da der ikke er nogen region tilknyttet tid firma. Kontakt KTC.'));
  }
}

/**
 * Form callback for cancelling a subscription.
 */
function ktc_crm_subscription_cancel_form($form, &$form_state, $account, $product_nid) {
  if (_ktc_crm_is_ktc_member()) {
    return array();
  }

  $form = array();

  if ($product = node_load($product_nid)) {
    if ($product_uuid = _ktc_crm_get_uuid('node', $product)) {
      $user_uuid = _ktc_crm_get_uuid('user', $account);
      $subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);
      if (isset($subscriptions[$product_uuid])) {
        $form_state['subscriptiondto'] = $subscriptions[$product_uuid];
      }
    }
  }

  $warning = '';
  if ($field = field_get_items('node', $product, 'field_cancel_warning')) {
    $warning = $field[0]['value'];
  }

  $form['message'] = array(
    '#type' => 'item',
    '#markup' => $warning,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Opsig nu'),
    '#suffix' => l(t('Annullér'), $_SERVER['HTTP_REFERER']),
    '#attributes' => array('class' => array('btn-warning')),
  );

  return $form;
}

/**
 * Form callback for cancelling a subscription.
 */
function ktc_crm_subscription_cancel_form_submit($form, &$form_state) {
  $subscriptiondto = $form_state['subscriptiondto'];
  $subscriptiondto->EndDate = date('Y-m-d\TH:i:s\Z', time());

  ktc_crm_update_user_subscription($subscriptiondto);

  global $user;
  drupal_goto('user/' . $user->uid . '/abonnementer');
}

/**
 * Admin form for subscription ui.
 */
function ktc_subscription_ui_admin_form($form, &$form_state) {
  $form['#tree'] = TRUE;
  $values = variable_get('ktc_subscription_ktc_membership', array());

  $form['ktc_subscription_ktc_membership'] = array(
    '#type' => 'fieldset',
    '#title' => t('Indstillinger for KTC medlemsskab'),
    '#description' => 'Her skal du angive UUIDer for de relevante produkter fra CRM. KTC Medlemskontingent UUIDet skal tilføjet til det produkt der oprettes som typen "KTC Medlemsskab"',
  );

  $form['ktc_subscription_ktc_membership']['tm_uuid'] = array(
    '#type' => 'textfield',
    '#title' => 'T&M produkt UUID',
    '#default_value' => !empty($values) ? $values['tm_uuid'] : '',
  );

  $regions_vocab = taxonomy_vocabulary_machine_name_load('regioner');
  $regions = taxonomy_term_load_multiple(array(), array('vid' => $regions_vocab->vid));

  foreach ($regions as $region) {
    $form['ktc_subscription_ktc_membership']['region'][$region->tid] = array(
      '#type' => 'fieldset',
    );
    $form['ktc_subscription_ktc_membership']['region'][$region->tid]['uuid'] = array(
      '#type' => 'textfield',
      '#title' => 'Region ' . $region->name . ' produkt UUID',
      '#default_value' => !empty($values) ? $values['region'][$region->tid]['uuid'] : '',
    );
    $form['ktc_subscription_ktc_membership']['region'][$region->tid]['name'] = array(
      '#type' => 'textfield',
      '#title' => 'Region ' . $region->name . ' kredsnavn',
      '#default_value' => !empty($values) ? $values['region'][$region->tid]['name'] : '',
    );
  }

  return system_settings_form($form);
}

/**
 * Get a list of products.
 */
function ktc_subscription_ui_get_product_list($type) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'product')
    ->fieldCondition('field_product_type', 'value', $type);
  $result = $query->execute();

  $nodes = array();

  if (isset($result['node'])) {
    foreach (node_load_multiple(array_keys($result['node'])) as $node) {
      // Filter out products without crm uuid. And strtolower the value.
      if ($field = field_get_items('node', $node, 'field_crm_uuid')) {
        $node->field_crm_uuid[LANGUAGE_NONE][0]['value'] = strtolower($field[0]['value']);

        $nodes[$node->nid] = $node;
      }
    }
  }

  return $nodes;
}

/**
 * Validate EAN numbers.
 */
function ktc_subscription_ui_validate_ean($ean) {
  $get_ean_check_digit = function($param) {
    $sum = 0;
    $odd = TRUE;

    for ($i = 11; $i >= 0; $i--) {
      $val  = intval(substr($param, $i, 1));
      $val *= ($odd ? 3 : 1);
      $odd = !$odd;

      $sum += $val;
    }

    $check = 10 - ($sum % 10);

    return ($check == 10 ? 0 : $check);
  };

  $valid = preg_match("/^\d{13}$/", $ean);
  $valid = $valid && (substr($ean, 12) == $get_ean_check_digit(substr($ean, 0, 12)));

  return $valid;
}
