<?php
/**
 * @file
 * Code for the KTC Subscriptions UI feature.
 */

include_once 'ktc_subscription_ui.features.inc';
/**
 * @file
 * KTC Subscription UI module.
 */

/**
 * Implements hook_menu().
 */
function ktc_subscription_ui_menu() {
  $items['admin/ktc/subscription'] = array(
    'title' => 'Abonnementer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user/%user/abonnementer'] = array(
    'title' => 'Abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(1),
    'page callback' => 'ktc_subscription_ui_page',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/abonnementer/%/edit'] = array(
    'title' => 'Abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/abonnementer/%/add'] = array(
    'title' => 'Abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/abonnementer/%/cancel'] = array(
    'title' => 'Abonnementer',
    'description' => 'Håndter abonnementer',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_crm_subscription_cancel_form', 1, 3),
  );

  $items['abonnementer'] = array(
    'access callback' => TRUE,
    'page callback' => 'ktc_subscription_ui_redirect',
  );

  $items['user/%user/medlemskab'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter KTC medlemskab',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array(1),
    'page callback' => 'ktc_subscription_ui_page',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/medlemskab/%/edit'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter medlemskab',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/medlemskab/%/add'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter medlemskab',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_form', 1, 3),
  );

  $items['user/%user/medlemskab/%/cancel'] = array(
    'title' => 'KTC medlemskab',
    'description' => 'Håndter medlemskab',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_crm_subscription_cancel_form', 1, 3),
  );

  $items['admin/config/services/ktc-crm_product-role-relation'] = array(
    'title' => t('KTC CRM Product Role Relation'),
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_subscription_ui_product_role_relation_form'),
    'type' => MENU_LOCAL_TASK
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ktc_subscription_ui_theme() {
  return array(
    'ktc_subscription_ui_page' => array(
      'template' => 'ktc-crm-subscriptions-page',
    ),
  );
}

/**
 * Redirect to current users subscription for specified product.
 */
function ktc_subscription_ui_redirect($product_id = '') {
  global $user;

  // If the user is logged in, redirect to the subscription page.
  if ($user->uid) {
    drupal_goto("user/$user->uid/abonnementer/$product_id");
  }
  else {
    drupal_set_message('Du skal logge ind for at kunne se dine abonnementer');
    drupal_goto('user/login', array('query' => array('destination' => "abonnementer/$product_id")));
  }
}

/**
 * Page callback, user subscriptions overview.
 */
function ktc_subscription_ui_page($account) {
  $args = array();

  $type = 'subscription';
  if (arg(2) == 'medlemskab') {
    $type = 'ktc_membership';
  }

  $args['subscription_nodes'] = ktc_subscription_ui_get_product_list($type);
  $args['user_subscriptions'] = ktc_crm_subscriptions_fetch_user_subscriptions($account);

  if ($args['user_subscriptions'] == 'error') {
    drupal_set_message('Der er sket en teknisk fejl. Det var ikke muligt at hente en oversigt over dine eksisterende abonnementer. Prøv venligst igen senere.', 'error');
  }

  return theme('ktc_subscription_ui_page', $args);
}

/**
 * Form callback for creating/editing a subscription.
 */
function ktc_subscription_ui_form($form, &$form_state, $account, $product_nid) {
  $css = '
      .container-inline-date {clear: none; float: left;}
      #edit-invoiceaccount-hierarchical-select-selects-0 {display: none;}
      #edit-invoiceaccount-hierarchical-select-selects-1 option:first-child {display: none;}
      #edit-submit {display: block; clear: left; margin-top: 10px; float: left; margin-top: 10px;}
    ';
  drupal_add_css($css, 'inline');

  $form = array();

  $form['back'] = array(
    '#type' => 'item',
    '#markup' => '<a href="' . url('user/' . $account->uid . '/' . arg(2)) . '" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Tilbage</a>',
  );
  if ($product = node_load($product_nid)) {

    if ($field = field_get_items('node', $product, 'field_product_type')) {
      $ktc_membership = ($field[0]['value'] == 'ktc_membership');
      $form_state['ktc_membership'] = $ktc_membership;
    }

    $form['text'] = array(
      '#type' => 'item',
      '#markup' => render(field_view_field('node', $product, 'body', array('label' => 'hidden'))),
    );

    $product_uuid = _ktc_crm_get_uuid('node', $product);
  }

  if (!$product_uuid) {
    drupal_set_message('Der er sket en fejl, prøv venligst igen senere. Hvis problemet vedvarer kontakt da KTC.', 'error');
    drupal_goto($_SERVER['HTTP_REFERER']);
  }

  $user_uuid = _ktc_crm_get_uuid('user', $account);

  // Find / create a SubscripitonDto.
  $subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);
  if (isset($subscriptions[$product_uuid])) {
    $form_state['subscriptiondto'] = $subscriptions[$product_uuid];
    $is_new = FALSE;
  }
  else {
    $form_state['subscriptiondto'] = new \KTC\Subscription\SubscriptionDto(NULL);
    $form_state['subscriptiondto']->ProductId = $product_uuid;
    $form_state['subscriptiondto']->RecipientId = $user_uuid;
    $form_state['subscriptiondto']->Abonnementsansvarlig = $user_uuid;
    $form_state['subscriptiondto']->OtherAddress = new \KTC\Subscription\AddressDto();
    $is_new = TRUE;
  }

  // There is a problem with fethcing data from crm.
  if (arg(4) == 'edit' && $is_new) {
    drupal_set_message('Der er sket en fejl, prøv venligst igen senere. Hvis problemet vedvarer kontakt da KTC.', 'error');
    drupal_goto($_SERVER['HTTP_REFERER']);
  }

  $form_state['subscriptiondto']->KundensReference = substr($account->name, 0, 30);

  $vocab = taxonomy_vocabulary_machine_name_load('accounts');
  $invoiceaccount = ktc_crm_account_load_from_uuid($form_state['subscriptiondto']->InvoiceAccountId);

  if (!$invoiceaccount) {
    $invoiceaccount = _ktc_crm_account_get_users_account($account);
  }

  if (!$invoiceaccount) {
    drupal_set_message(t('Du mangler at udfylde nogle informationer i din brugerprofil.') . ' ' . l(t('Tryk her for at redigere.'), 'user/' . $account->uid . '/edit'), 'warning');
    drupal_goto('user/' . $account->uid . '/' . arg(2));
  }

  $top_level_account = ktc_crm_account_load_top_level_account($invoiceaccount);
  $user_data = ktc_users_get_user_info_personal_data($account);
  if ($field = field_get_items('node', $product, 'field_text_before_invoiceaccount')) {
    $form['text_before_invoiceaccount'] = array(
      '#markup' => '<div>' . $field[0]['value'] . '</div><br />',
    );
  }
  $form['subscriptionform'] = array(
    '#type' => 'vertical_tabs',
  );
  $form['fakturering'] = array(
    '#type' => 'fieldset',
    '#title' => t('Fakturering'),
    '#collapsible' => TRUE,
    '#group' => 'subscriptionform'
   );
  $form['fakturering']['invoiceaccount'] = array(
    '#type' => 'value',
    '#prefix' => '<div class="form-item form-group"><h5>Faktureringoplysninger:</h5><b><p>' . $user_data['firstname'] . ' ' .  $user_data['lastname'] . '</p><label>Firma</label><p>' . $top_level_account->name . '<br />' . $invoiceaccount->name . '<br />' . ktc_users_get_user_address($account, 'Work') . '</p></b>',
    '#suffix' => '</div>',
    '#value' => array($invoiceaccount->tid),
    '#group' => 'subscriptionform'
  );

  $form['fakturering']['ktc_ean'] = array(
     '#tree' => FALSE,
     '#type' => 'fieldset',
     '#title' => t('EAN fakturering'),
     //'#group' => 'subscriptionform'
   );
  $form['fakturering']['ktc_ean']['ean_bill'] = array(
    '#type' => 'radios',
    '#options' => array(1 => t('Yes'), 0 => t('No')),
    '#default_value' => isset($form_state['ean_bill'])? $form_state['ean_bill'] : null,
    '#attributes' => array('class' => array('ean_billing')),
    '#group' => 'subscriptionform'
  );
  $form['fakturering']['ktc_ean']['ean'] = array(
    '#title' => t('Indtast EAN nr:'),
    '#type' => 'textfield',
    '#default_value' => $form_state['subscriptiondto']->EAN,
    '#attributes' => array('id' => array('field_ean')),
    '#group' => 'subscriptionform'
  );

  if ($ktc_membership) {
    $region_uuid = '';
    $region_name = '';

    if ($top_level_account && $field = field_get_items('taxonomy_term', $top_level_account, 'field_regioner')) {
      $region_tid = $field[0]['tid'];

      $ktc_membership_settings = variable_get('ktc_subscription_ktc_membership', array());

      if (isset($ktc_membership_settings['region'][$region_tid])) {
        $region_uuid = $ktc_membership_settings['region'][$region_tid]['uuid'];
        $region_name = $ktc_membership_settings['region'][$region_tid]['name'];
      }
    }

    $prefix = '';

    if ($field = field_get_items('node', $product, 'field_text_before_membership')) {
      $prefix = '<div>' . $field[0]['value'] . '</div>';
    }
    $form['ktc_membership'] = array(
      '#type' => 'fieldset',
      '#title' => t('Medlemskab'),
      '#collapsible' => TRUE,
      '#group' => 'subscriptionform'
    );

    $form['ktc_membership']['ktc_membership_type'] = array(
      '#tree' => FALSE,
      '#type' => 'fieldset',
      '#title' => t('Vælg medlemsparagraf'),
    );
    $membership_categories = ktc_crm_webuser_membership_categories();

    $membership_category = '';
    if ($field = field_get_items('user', $account, 'field_membership_ktc_category')) {
      $membership_category = $field[0]['value'];
    }

    $form['ktc_membership']['ktc_membership_type']['ktc_membership_category'] = array(
      '#title' => 'Vælg medlemsparagraf',
      '#type' => 'select',
      '#prefix' => $prefix,
      '#required' => TRUE,
      '#options' => $membership_categories,
      '#default_value' => $membership_category,
    );

    $form['ktc_membership']['kreds'] = array(
      '#tree' => FALSE,
      '#type' => 'fieldset',
      '#title' => t('Kredsmedlemskab'),
    );

    if ($field = field_get_items('node', $product, 'field_text_before_region')) {
      $form['ktc_membership']['kreds']['text_before_region'] = array(
        '#markup' => '<div>' . $field[0]['value'] . '</div><br />',
      );
    }

    $form['ktc_membership']['kreds']['region'] = array(
      '#type' => 'value',
      '#prefix' => '<b>' . $region_name . '</b>',
      '#value' => $region_uuid,
    );
  }
  $form['levering'] = array(
      '#type' => 'fieldset',
      '#title' => t('Levering'),
      '#collapsible' => TRUE,
      '#group' => 'subscriptionform'
  );
  $form['levering']['title'] = array(
      '#markup' => '<div><h5>Levering</h5></div><br />',
    );
  $recipient_addresses['Work'] = array(
    'Arbejde',
    ktc_users_get_user_address($account, 'Work'),
    l(t('ret adresse'), 'user/' . $account->uid . '/edit', array('query' => array('destination' => current_path()))),
  );

  $recipient_addresses['Private'] = array(
    'Privat',
    ktc_users_get_user_address($account, 'Private'),
    l(t('ret adresse'), 'user/' . $account->uid . '/edit', array('query' => array('destination' => current_path()))),
  );

  $recipient_addresses['Other'] = array(
    'Anden leveringsadresse',
    'Udfyldes herunder.',
    '',
  );

  if ($field = field_get_items('node', $product, 'field_text_before_address')) {
    $form['levering']['text_before_address'] = array(
      '#markup' => '<div>' . $field[0]['value'] . '</div><br />',
    );
  }

  $form['levering']['recipient_address'] = array(
    '#prefix' => '<label>Vælg leveringsadresse *</label>',
    '#type' => 'tableselect',
    '#multiple' => FALSE,
    '#header' => array('Leveres til', 'Adresse', ''),
  //  '#required' => TRUE,
    '#options' => $recipient_addresses,
    '#default_value' => $form_state['subscriptiondto']->RecipientAddress,
  );

  $text_before_address = 'Udfyldes kun, hvis "Anden leveringsadresse" vælges ovenfor.';

  if ($field = field_get_items('node', $product, 'field_text_before_other_address')) {
    $text_before_other_address = $field[0]['value'];
  }

  $form['levering']['other_address'] = array(
    '#type' => 'fieldset',
    '#title' => 'Anden leveringsadresse',
    '#description' => $text_before_other_address,
    '#tree' => FALSE,
  );

  $form['levering']['other_address']['address_line_1'] = array(
    '#title' => t('Vejnavn'),
    '#type' => 'textfield',
    '#default_value' => $form_state['subscriptiondto']->OtherAddress->AddressLine1,
  );

  $form['levering']['other_address']['address_line_2'] = array(
    '#title' => t('Vejnavn 2'),
    '#type' => 'textfield',
    '#default_value' => $form_state['subscriptiondto']->OtherAddress->AddressLine2,
  );

  $form['levering']['other_address']['postal_code'] = array(
    '#title' => t('Postnummer'),
    '#type' => 'textfield',
    '#default_value' => $form_state['subscriptiondto']->OtherAddress->PostalCode,
  );

  $form['levering']['other_address']['city'] = array(
    '#title' => t('By'),
    '#type' => 'textfield',
    '#default_value' => $form_state['subscriptiondto']->OtherAddress->City,
  );

  $form['levering']['other_address']['country'] = array(
    '#title' => t('Land'),
    '#type' => 'textfield',
    '#default_value' => $form_state['subscriptiondto']->OtherAddress->Country,
  );

  if ($field = field_get_items('node', $product, 'field_text_before_submit')) {
    $form['text_before_submit'] = array(
      '#prefix' => '<div><h5> Bekræfter oplysninger og betingelser:</h5></div>',
      '#type' => 'checkbox',
      '#title' => $field[0]['value'] . ' *',
     // '#required' => TRUE,
    );
  }
  if ($field = field_get_items('node', $product, 'field_description_before_submit')) {
    $form['text_before_submit']['#description'] = $field[0]['value'];
  }
$form['dates'] = array(
      '#type' => 'fieldset',
      '#title' => t('Start- og sultdato'),
      '#collapsible' => TRUE,
      '#group' => 'subscriptionform'
  );
  $form['dates']['title'] = array(
      '#markup' => '<div><h5>Start- og sultdato:</h5></div>',
    );
  // Generate default value for date_popup.
  $startdate = str_replace(array('T', 'Z'), array(' ', ''), $form_state['subscriptiondto']->StartDate);
  // If there is no startdate, assume that this is a new subscription and
  // prefill the value with 'now'.
  if (!$startdate) {
    $startdate = date('Y-m-d H:i:s', strtotime('now'));
  }
  $enddate = str_replace(array('T', 'Z'), array(' ', ''), $form_state['subscriptiondto']->EndDate);
  // Same for enddate, if none is set, generate appropriate prefill values.
  // If the enddate specified is before today, set the field empty.
  if (!$form_state['subscriptiondto']->EndDate || strtotime($enddate) < time()) {
    $enddate = '';
  }

  // If the product allows showing a datepicker add that form item.
  $field = field_get_items('node', $product, 'field_show_datepicker');
  if ($field && $field[0]['value']) {
    if ($field = field_get_items('node', $product, 'field_text_before_date')) {
      $form['dates']['text_date'] = array(
        '#type' => 'item',
        '#markup' => $field[0]['value'],
      );
    }

    $form['dates']['title_date'] = array(
        '#type' => 'item',
        '#markup' =>'<div> <h5>Indrast startdato og eventuel slutdato:</h5></div>',
      );
    
    $form['dates']['startdate'] = array(
      '#title' => 'Startdato',
      '#type' => 'date_popup',
      '#date_format' => 'd/m/Y',
      '#date_year_range' => ':+20',
      '#default_value' => $startdate,
      '#date_label_position' => 'invisible',
    );
    $form['dates']['enddate'] = array(
      '#title' => 'Slutdato',
      '#type' => 'date_popup',
      '#date_format' => 'd/m/Y',
      '#date_year_range' => ':+20',
      '#default_value' => $enddate,
      '#date_label_position' => 'invisible',
      '#suffix' => '<br /><br /><br />',
    );
  }
  else {
    // If not, we just set the enddate to somewhere in the future.
    $form['dates']['startdate'] = array(
      '#type' => 'value',
      '#value' => $startdate,
    );

    // If no enddate is set on the subscription object, set one well into
    // the future.
    if (!$form_state['subscriptiondto']->EndDate) {
      $enddate = '';
    }

    $form['dates']['enddate'] = array(
      '#type' => 'value',
      '#value' => $enddate,
    );
  }

  $form['#attached']['js'] = array(
    drupal_get_path('module', 'ktc_subscription_ui') . '/ktc_subscription_ui.js', array(
      'type' => 'file',
    ),
  );

  $submit = $is_new ? t('Opret abonnement') : t('Gem abonnement');
  if ($ktc_membership) {
    $submit = $is_new ? t('Opret medlemskab') : t('Gem medlemskab');
  }

  $form['submit'] = array(
    '#value' => $submit,
    '#type' => 'submit',
  );

  $form_state['account'] = $account;
  $form_state['product'] = $product;

  return $form;
}

/**
 * Submit handler for create/update subscription form.
 */
function ktc_subscription_ui_form_submit(&$form, &$form_state) {
  $subscriptiondto = $form_state['subscriptiondto'];

  $invoiceaccount = taxonomy_term_load($form_state['values']['invoiceaccount'][0]);

  $invoiceaccountid = _ktc_crm_get_uuid('taxonomy_term', $invoiceaccount);

  $subscriptiondto->InvoiceAccountId = $invoiceaccountid;
  $subscriptiondto->EAN = $form_state['values']['ean'];
  $subscriptiondto->RecipientAddress = $form_state['values']['recipient_address'];

  $addressdto = new KTC\Subscription\AddressDto($form_state['values']['crm_uuid']);

  $addressdto->AddressLine1 = $form_state['values']['address_line_1'];
  $addressdto->AddressLine2 = $form_state['values']['address_line_2'];
  $addressdto->PostalCode = $form_state['values']['postal_code'];
  $addressdto->City = $form_state['values']['city'];
  $addressdto->Country = $form_state['values']['country'];

  $subscriptiondto->OtherAddress = $addressdto;

  $subscriptiondto->StartDate = date('Y-m-d\TH:i:s\Z', strtotime($form_state['values']['startdate']));
  // Only set enddate, if one is selected.
  if ($form_state['values']['enddate']) {
    $subscriptiondto->EndDate = date('Y-m-d\TH:i:s\Z', strtotime($form_state['values']['enddate']));
  }
  else {
    $subscriptiondto->EndDate = NULL;
  }

  // Default redirect path.
  $overview_path = 'abonnementer';

  $account = $form_state['account'];
  $account = user_load($account->uid);
  $product = $form_state['product'];

  // If this is a ktc_membership, handle the extra products aswell.
  if ($form_state['ktc_membership']) {
    // Update the additional products to the membership.
    ktc_crm_subscription_update_membership_extras($subscriptiondto, $form_state['values']['region']);

    // Update the membership category.
    ktc_crm_webuser_update_membership_category($account, $form_state['values']['ktc_membership_category']);

    // Redirect to membership overview.
    $overview_path = 'medlemskab';
  }

  $return = ktc_crm_update_user_subscription($subscriptiondto);

  //add role to user
  $related_role = variable_get('ktc_subscription_product_' . $product->nid . '_role_relation');
  if ($related_role && !user_has_role($related_role, $account)) {
    $new_roles = $account->roles;
    $new_roles[$related_role] = user_role_load($related_role)->name;
    user_save($account, array('roles' => $new_roles));
  }

  if ($return == 'error') {
    drupal_set_message('Der er sket en teknisk fejl. Det var ikke muligt at oprette det ønskede abonnement. Prøv venligst igen senere.', 'error');
    $form_state['rebuild'] = TRUE;
  }
  else {
    drupal_goto('user/' . $account->uid . '/' . $overview_path);
  }
}

/**
 * Validation handler for create/update subscription form.
 */
function ktc_subscription_ui_form_validate(&$form, &$form_state) {
  if ($form_state['values']['enddate'] && strtotime($form_state['values']['enddate']) < time()) {
    form_set_error('enddate', t('Du skal vælge en dato i fremtiden'));
  }

  if ($form_state['values']['ean_bill'] == 1 && !ktc_subscription_ui_validate_ean($form_state['values']['ean'])) {
    form_set_error('ean', t('Det indtastede EAN nummer er ikke korrekt.'));
  }
  if (!$form_state['values']['region'] && $form_state['ktc_membership']) {
    form_set_error('region', t('Kredsmedlemsskabet kunne ikke bestemmes, da der ikke er nogen region tilknyttet dit firma. Kontakt KTC.'));
  }
  if (!$form_state['values']['recipient_address']) {
    form_set_error('recipient_address', t('Du mangler at vælge leveringsadresse til dit aboniment'));
  }
  if (!$form_state['values']['text_before_submit']) {
    form_set_error('text_before_submit', t('Du skal ælge en sludato til dit abonnement som er senere end dags dato'));
  }
}

/**
 * Form callback for cancelling a subscription.
 */
function ktc_crm_subscription_cancel_form($form, &$form_state, $account, $product_nid) {
  $form = array();

  if ($product = node_load($product_nid)) {
    if ($field = field_get_items('node', $product, 'field_product_type')) {
      $ktc_membership = ($field[0]['value'] == 'ktc_membership');
      $form_state['ktc_membership'] = $ktc_membership;
    }

    if ($product_uuid = _ktc_crm_get_uuid('node', $product)) {
      $user_uuid = _ktc_crm_get_uuid('user', $account);
      $subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);
      if (isset($subscriptions[$product_uuid])) {
        $form_state['subscriptiondto'] = $subscriptions[$product_uuid];
      }
    }

    $form_state['account'] = $account;
    $form_state['product'] = $product;
  }
  if (!$form_state['subscriptiondto']) {
    drupal_set_message('Der er sket en fejl, prøv venligst igen senere. Hvis problemet vedvarer kontakt da KTC.', 'error');
    drupal_goto($_SERVER['HTTP_REFERER']);
  }

  $warning = '';
  if ($field = field_get_items('node', $product, 'field_cancel_warning')) {
    $warning = $field[0]['value'];
  }

  $form['message'] = array(
    '#type' => 'item',
    '#markup' => $warning,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Opsig nu'),
    '#suffix' => l(t('Annullér'), $_SERVER['HTTP_REFERER']),
    '#attributes' => array('class' => array('btn-warning')),
  );

  return $form;
}

/**
 * Form callback for cancelling a subscription.
 */
function ktc_crm_subscription_cancel_form_submit($form, &$form_state) {
  $subscriptiondto = $form_state['subscriptiondto'];
  $subscriptiondto->EndDate = date('Y-m-d\TH:i:s', time());

  $account = $form_state['account'];
  $account = user_load($account->uid);
  $product = $form_state['product'];

  // Default redirect path.
  $overview_path = 'abonnementer';

  if ($form_state['ktc_membership']) {
    // Update the additional products to the membership.
    ktc_crm_subscription_update_membership_extras($subscriptiondto, $form_state['values']['region']);
    ktc_crm_webuser_cancel_membership($account);

    // Redirect to membership overview.
    $overview_path = 'medlemskab';
  }

  ktc_crm_update_user_subscription($subscriptiondto);

  //remove role from account
  $related_role = variable_get('ktc_subscription_product_' . $product->nid . '_role_relation');
  if ($related_role && user_has_role($related_role, $account)) {
    //check if there is no other product related with account, that hold to this role
    $user_subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);

    //unset remove the subscription that we are currently cancelling
    $product_uuid = field_get_items('node', $product, 'field_crm_uuid');
    if ($product_uuid) {
      unset($user_subscriptions[strtolower($product_uuid[0]['value'])]);
    }
    $all_products = ktc_subscription_ui_get_product_list('subscription');

    foreach($all_products as $prod) {
      $product_uuid = field_get_items('node', $prod, 'field_crm_uuid');
      if ($product_uuid && isset($user_subscriptions[$product_uuid[0]['value']])) {
        if ($user_subscriptions[$product_uuid[0]['value']]->is_active) {
          if ($related_role == variable_get('ktc_subscription_product_' . $prod->nid . '_role_relation')) {
            $related_role = NULL;//cancelling role removing
          }
        }
      }
    }

    //check if we still need to remote the role from a user
    if ($related_role) {
      $new_roles = array();
      foreach($account->roles as $id => $name) {
        if ($id != $related_role) {
          $new_roles[$id] = $name;
        }
      }
      user_save($account, array('roles' => $new_roles));
    }
  }


  drupal_goto('user/' . $account->uid . '/' . $overview_path);
}

/**
 * Update the extra products to a membership.
 *
 * A membership requires 2 additional subscriptions. This function handle these
 * based upon the primary subscription.
 */
function ktc_crm_subscription_update_membership_extras($subscriptiondto, $region_product_uuid = FALSE) {
  global $user;
  $account = user_load($user->uid);

  $ktc_membership_settings = variable_get('ktc_subscription_ktc_membership', array());

  $subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);

  if (!$region_product_uuid) {
    $region_subscriptiondto = _ktc_crm_subscription_fetch_region_subscription($account);

    $region_product_uuid = $region_subscriptiondto->ProductId;
  }

  if ($region_product_uuid) {
    $extra_products[] = strtolower($region_product_uuid);
  }

  $extra_products[] = strtolower($ktc_membership_settings['tm_uuid']);

  // Iterate over the extra products.
  foreach ($extra_products as $product_uuid) {
    // As the extra subscriptions are based on the primary subscription, clone
    // the object to get the values.
    $extra_subscriptiondto = clone $subscriptiondto;

    // We need the crm uuid for the subscription in order to update the
    // subscription in crm.
    $extra_crm_id = $subscriptions[$product_uuid]->CrmId;

    // Set the correct uuids to the subscription.
    $extra_subscriptiondto->CrmId = $extra_crm_id;
    $extra_subscriptiondto->ProductId = $product_uuid;

    // Save it.
    ktc_crm_update_user_subscription($extra_subscriptiondto);
  }
}

/**
 * Helper, determine region subscription in current subscriptions.
 */
function _ktc_crm_subscription_fetch_region_subscription($account) {
  // All the users current subscriptions.
  $subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);

  // Find all region product uuids.
  $ktc_membership_settings = variable_get('ktc_subscription_ktc_membership', array());

  if (isset($ktc_membership_settings['region'])) {
    foreach ($ktc_membership_settings['region'] as $region) {
      if ($region['uuid']) {
        $region_uuids[] = strtolower($region['uuid']);
      }
    }
  }

  // Iterate over subscriptions, find out which one is a region subscription.
  foreach ($subscriptions as $product_uuid => $subscription) {
    if (in_array($product_uuid, $region_uuids)) {
      return $subscription;
    }
  }

  return FALSE;
}

/**
 * Admin form for subscription ui.
 */
function ktc_subscription_ui_admin_form($form, &$form_state) {
  $form['#tree'] = TRUE;
  $values = variable_get('ktc_subscription_ktc_membership', array());

  $form['ktc_subscription_ktc_membership'] = array(
    '#type' => 'fieldset',
    '#title' => t('Indstillinger for KTC medlemsskab'),
    '#description' => 'Her skal du angive UUIDer for de relevante produkter fra CRM. KTC Medlemskontingent UUIDet skal tilføjet til det produkt der oprettes som typen "KTC Medlemsskab"',
  );

  $form['ktc_subscription_ktc_membership']['tm_uuid'] = array(
    '#type' => 'textfield',
    '#title' => 'T&M produkt UUID',
    '#default_value' => !empty($values) ? $values['tm_uuid'] : '',
  );

  $regions_vocab = taxonomy_vocabulary_machine_name_load('regioner');
  $regions = taxonomy_term_load_multiple(array(), array('vid' => $regions_vocab->vid));

  foreach ($regions as $region) {
    $form['ktc_subscription_ktc_membership']['region'][$region->tid] = array(
      '#type' => 'fieldset',
    );
    $form['ktc_subscription_ktc_membership']['region'][$region->tid]['uuid'] = array(
      '#type' => 'textfield',
      '#title' => 'Region ' . $region->name . ' produkt UUID',
      '#default_value' => !empty($values) ? $values['region'][$region->tid]['uuid'] : '',
    );
    $form['ktc_subscription_ktc_membership']['region'][$region->tid]['name'] = array(
      '#type' => 'textfield',
      '#title' => 'Region ' . $region->name . ' kredsnavn',
      '#default_value' => !empty($values) ? $values['region'][$region->tid]['name'] : '',
    );
  }

  return system_settings_form($form);
}

/**
 * Get a list of products.
 */
function ktc_subscription_ui_get_product_list($type) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'product')
    ->fieldCondition('field_product_type', 'value', $type);
  $result = $query->execute();

  $nodes = array();

  if (isset($result['node'])) {
    foreach (node_load_multiple(array_keys($result['node'])) as $node) {
      // Filter out products without crm uuid. And strtolower the value.
      if ($field = field_get_items('node', $node, 'field_crm_uuid')) {
        $node->field_crm_uuid[LANGUAGE_NONE][0]['value'] = strtolower($field[0]['value']);

        $nodes[$node->nid] = $node;
      }
    }
  }

  return $nodes;
}

/**
 * Validate EAN numbers.
 */
function ktc_subscription_ui_validate_ean($ean) {
  $get_ean_check_digit = function($param) {
    $sum = 0;
    $odd = TRUE;

    for ($i = 11; $i >= 0; $i--) {
      $val  = intval(substr($param, $i, 1));
      $val *= ($odd ? 3 : 1);
      $odd = !$odd;

      $sum += $val;
    }

    $check = 10 - ($sum % 10);

    return ($check == 10 ? 0 : $check);
  };

  $valid = preg_match("/^\d{13}$/", $ean);
  $valid = $valid && (substr($ean, 12) == $get_ean_check_digit(substr($ean, 0, 12)));

  return $valid;
}

/**
 * Form facilitating product -> user_role relation
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function ktc_subscription_ui_product_role_relation_form($form, $form_state) {
  $type = 'subscription';
  $products = ktc_subscription_ui_get_product_list($type);

  $roles = user_roles(TRUE);

  foreach ($products as $nid => $product) {
    $form['product_fieldset' . $nid] = array(
      '#type' => 'fieldset',
      '#title' => t('@title [nid: @nid]', array('@title' => $product->title, '@nid' => $nid)),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );

    $form['product_fieldset' . $nid][] = array(
      '#markup' => l($product->title, 'node/' . $nid, array('attributes' => array('target' => '_blank'))) . ' ' . t('is related to role'),
    );

    $form['product_fieldset' . $nid]['ktc_subscription_product_' . $nid . '_role_relation'] = array(
      '#type' => 'select',
      '#options' => $roles,
      '#empty_value' => 0,
      '#default_value' => variable_get('ktc_subscription_product_' . $nid . '_role_relation', 0),
    );
  }

  return system_settings_form($form);
}

/**
 * Updates the user roles based on the user subscriptions (products)
 *
 * @param $account
 */
function ktc_subscription_ui_update_user_roles($account) {
  //getting all available products
  $type = 'subscription';
  $products = ktc_subscription_ui_get_product_list($type);

  //getting all available subscriptions
  $user_subscriptions = ktc_crm_subscriptions_fetch_user_subscriptions($account);

  //calculating which roles to add/remove
  $roles_to_remove = array();
  $roles_to_add = array();
  foreach ($products as $product) {
    $related_role = variable_get('ktc_subscription_product_' . $product->nid . '_role_relation');
    if ($related_role) {
      $roles_to_remove[] = $related_role;
    }

    $product_uuid = field_get_items('node', $product, 'field_crm_uuid');
    if ($product_uuid && isset($user_subscriptions[$product_uuid[0]['value']])) {
      if ($user_subscriptions[$product_uuid[0]['value']]->is_active) {
        $roles_to_add[] = $related_role;
      }
    }
  }
  $roles_to_remove = array_unique($roles_to_remove);
  $roles_to_add = array_unique($roles_to_add);

  //removing those that are not present in the add array
  $roles_to_remove = array_diff($roles_to_remove, $roles_to_add);
  if (!empty($roles_to_remove)) {
    foreach ($account->roles as $id => $name) {
      if (!in_array($id, $roles_to_remove)) {
        $new_roles[$id] = $name;
      }
    }
    user_save($account, array('roles' => $new_roles));
    $account = user_load($account->uid);
  }

  //adding new roles
  if (!empty($roles_to_add)) {
    $new_roles = $account->roles;
    foreach ($roles_to_add as $role) {
      if (!user_has_role($role, $account)) {
        $new_roles[$role] = user_role_load($role)->name;
      }
    }
    user_save($account, array('roles' => $new_roles));
  }
}
