<?php
/**
 * @file
 * Code for the KTC signup block module.
 */

/**
 * Implements hook_block_info().
 */
function ktc_signup_block_block_info() {
  $blocks = array();

  $blocks['ktc_signup_link_block'] = array(
    'info' => t('KTC signup link blok'),
  );

  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function ktc_signup_block_block_view($delta = '') {
  $block = array();
  switch ($delta) {

    case 'ktc_signup_link_block':
      $block['subject'] = '';
      $block['content'] = ktc_signup_block_link_content();
      break;
  }
  return $block;
}

/**
 * KTC signup block link block callback.
 */
function ktc_signup_block_link_content() {
  global $user;
  $output = '';
  $nid = arg(1);
  $node = FALSE;
  if (is_numeric($nid)) {
    $node = node_load($nid);
  }
  if (isset($node->signup_status)) {
    // The node has been closed for signups, and the user has
    // signup permissions.  Let them know it's closed.
    if ($node && !$node->signup_status && !$direct_link = field_get_items('node', $node, 'field_link_to_signup')) {
      if (user_access('sign up for content')) {
        $output .= '<div>';
        // If they're logged in and already signed up, show their current
        // signup info and give them the option to cancel.
        if ($user->uid) {
          $signup = db_query("SELECT sl.*, n.title, u.name FROM {signup_log} sl INNER JOIN {node} n ON sl.nid = n.nid INNER JOIN {users} u ON sl.uid = u.uid WHERE sl.uid = :uid AND sl.nid = :nid", array(':uid' => $user->uid, ':nid' => $node->nid))->fetchObject();
          if (!empty($signup)) {
            $output .= _ktc_signup_block_get_cancel_link($signup);

          }
        }
        $output .= '</div>';
      }
    }
    elseif ($node && $node->signup_status && !$direct_link = field_get_items('node', $node, 'field_link_to_signup')) {

      if ($user->uid == 0) {
        // This is an anonymous user.
        if ($access = node_access('view', $node)) {
          $output .= '<div>
                        <h4>For medlem | <a href="/user?destination=node/' . $nid . '">Klik her </a>for at logge på så du kan tilmelde dig</h4>
                      </div>';

        }
      }
      else {
        // An authenticated user.

        // See if the user is already signed up for this node.
        $signup = db_query("SELECT sl.*, n.title, u.name, u.mail FROM {signup_log} sl INNER JOIN {node} n ON sl.nid = n.nid INNER JOIN {users} u ON sl.uid = u.uid WHERE sl.uid = :uid AND sl.nid = :nid", array(':uid' => $user->uid, ':nid' => $node->nid))->fetchObject();
        if (empty($signup)) {
          // Not yet signed up.
          if (user_access('sign up for content')) {
            $output .= '<div>';
            $output .= _ktc_signup_block_get_signup_link($node);
            $output .= '</div>';
          }
        }
        else {
          // Already signed up, display cancel link.
          $output .= '<div>';
          $output .= _ktc_signup_block_get_cancel_link($signup);

          $output .= '</div>';
        }
      }
    }
  }
  return $output;
}

/**
 * KTC signup block cancel link callback.
 */
function _ktc_signup_block_get_cancel_link($signup) {
  global $user;
  $output = '';
  $node = node_load($signup->nid);

  // Check permissions.
  $admin = _signup_menu_access($node, 'admin');
  $own = !empty($user->uid) && $user->uid == $signup->uid;
  $can_cancel = $admin || (user_access('cancel own signups') && $own);
  if ($can_cancel) {
    $destination = array('destination' => 'node/' . $signup->nid);
    $signup_token = signup_get_token($signup->sid, 'cancel');

    $output .= l(t('Afmeld'), "signup/cancel/$signup->sid/$signup_token",
                array(
                  'query' => $destination,
                  'attributes' => array('class' => array('btn', 'btn-default')),
                ));
  }
  return $output;
}

/**
 * KTC signup block get signup link callback.
 */
function _ktc_signup_block_get_signup_link($node) {
  $output = '';
  $now = new DateTime('now');

  if ($field_registration_deadline = field_get_items('node', $node, 'field_registration_deadline')) {
    $deadline = new DateTime($field_registration_deadline[0]['value']);
  }

  if ($field_arrangement_date = field_get_items('node', $node, 'field_arrangement_date')) {
    $arrangement_date = new DateTime($field_arrangement_date[0]['value']);
  }

  if ($field_registration_deadline = field_get_items('node', $node, 'field_registration_deadline')) {
    $deadline = new DateTime($field_registration_deadline[0]['value']);
  }

  if ($deadline && $now && ($now > $deadline) && ($now < $arrangement_date)) {
    $output = '<p>' . t('Fristen for tilmelding til dette arrangement er overskredet. Kontakt evt. arrangøren for "last minute" tilmelding.') . '</p>';
  }
  elseif($now > $arrangement_date) {
    $output = '';
  }
  else {
    module_load_include('inc', 'signup', 'includes/signup_form');
    $form = drupal_get_form('signup_form', $node, 'auth', FALSE);
    $output .= drupal_render($form);
  }

  return $output;
}

/**
 * Implements hook_form_alter().
 */
function ktc_signup_block_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'signup_node_admin_summary_form'
      || $form_id == 'signup_form'
      || $form_id == 'signup_node_settings_form'
      || $form_id == 'signup_broadcast_form') {
    $form['#theme'] = array('ktc_signup_admin_form');
  }
}

/**
 * Implements hook_theme().
 */
function ktc_signup_block_theme($existing, $type, $theme, $path) {
  $path = 'theme/';
  return array(
    'ktc_signup_admin_form' => array(
      'render element' => 'form',
      'template' => $path . 'ktc-signup-admin-form',
    ),
  );
}
