<?php
/**
 * @file
 * Code for the KTC Hearing notifications feature.
 */

include_once 'ktc_hearing_notifications.features.inc';
/**
 * @file
 * KTC Hearing notifications module.
 */

/**
 * Implements hook_menu().
 */
function ktc_hearing_notifications_menu() {
  $items['admin/config/content/ktc_hearings_notifications'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'KTC Høringer, notifikationer',
    'description' => 'Configure KTC Hearing notifications module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_hearing_notifications_settings'),
    'access arguments' => array('administer ktc hearings'),
    'file' => 'ktc_hearing_notifications.admin.inc',
  );
  return $items;
}
/**
 * Implements hook_form_alter().
 */
function ktc_hearing_notifications_form_alter(&$form, &$form_state, $form_id) {
  // Show token form in the node edit form for notifications.
  if ($form_id == 'ktc_hearings_notification_node_form') {
    $form['tokens'] = array(
      '#theme' => 'token_tree',
      '#token_types' => array('user', 'node'),
      '#global_types' => FALSE,
      '#click_insert' => FALSE,
      '#weight' => 50,
    );
  }
}

/**
 * Implements hook_cron().
 */
function ktc_hearing_notifications_cron() {
  // Only notify once a day.
  $cron_time = variable_get('ktc_hearing_notifications_cron_time', 1);

  $time_now = date('Ymd');

  if ($cron_time < $time_now) {
    $due_days = array(2, 14);

    foreach ($due_days as $days) {
      $hearings = _ktc_hearing_notifications_get_hearings_due($days);

      foreach ($hearings as $hearing_nid) {
        ktc_hearing_notifications_notify_users('notify-' . $days, node_load($hearing_nid));
      }
    }
  }

  variable_set('ktc_hearing_notifications_cron_time', $time_now);
}

/**
 * Get a list of hearings due in a specified number of days.
 */
function _ktc_hearing_notifications_get_hearings_due($days) {
  $date = date('Y-m-d', strtotime('+' . $days . 'day')) . '%';

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'hearing')
    ->fieldCondition('field_status', 'tid', KTC_HEARING_STATUS_OPEN)
    ->fieldCondition('field_attendee_deadlines', 'value', $date, 'LIKE');
  $result = $query->execute();

  if (isset($result['node'])) {
    return array_keys($result['node']);
  }

  return array();
}

/**
 * Implements hook_ktc_hearing_save().
 */
function ktc_hearing_notifications_ktc_hearing_save($hearing) {
  if ($hearing->status) {
    $hearing_status = ktc_hearing_get_status($hearing);
    if (isset($hearing->original)) {
      $original_status = ktc_hearing_get_status($hearing->original);
      if ($hearing_status == KTC_HEARING_STATUS_OPEN && $original_status == KTC_HEARING_STATUS_NEW) {
        ktc_hearing_notifications_notify_users('new_hearing', $hearing);
      }

      // Notifications on state change -->
      if ($hearing_status == KTC_HEARING_STATUS_APPROVAL && $original_status != KTC_HEARING_STATUS_APPROVAL) {
        ktc_hearing_notifications_notify_users('approval', $hearing);
      }

      if ($hearing_status == KTC_HEARING_STATUS_APPROVED && $original_status != KTC_HEARING_STATUS_APPROVED) {
        ktc_hearing_notifications_notify_users('approved', $hearing);
      }

      if ($hearing_status == KTC_HEARING_STATUS_KL_ANSWER && $original_status != KTC_HEARING_STATUS_KL_ANSWER) {
        ktc_hearing_notifications_notify_users('kl_answer', $hearing);
      }
      // <-- End notifications on state change.

      // Notifications on coordinator/chairman change -->
      if (serialize($hearing->original->field_responsible_admin) != serialize($hearing->field_responsible_admin)) {
        ktc_hearing_notifications_notify_users('change_coordinator', $hearing);
      }

      if (serialize($hearing->original->field_responsible_foreman) != serialize($hearing->field_responsible_foreman)) {
        ktc_hearing_notifications_notify_users('change_chairman', $hearing);
      }
      // <-- End notifications on coordinator/chairman change.
    }
  }
}

/**
 * Notify users on hearing.
 */
function ktc_hearing_notifications_notify_users($op, $hearing) {
  // The order of these roles define what notification the user will recieve.
  // If a user is both chairman and attendee, he will not recieve the normal
  // attendee mail, as only one notification is send per user.
  $attendee_roles = array(
    'responsible_foreman',
    'responsible_admin',
    'chairman',
    'coordinator',
    'attendees',
  );

  foreach ($attendee_roles as $field_name) {
    if ($field = field_get_items('node', $hearing, 'field_' . $field_name)) {
      $users[$field_name] = $field;
    }
  }

  $attendee_roles[] = 'creator';
  $users['creator'][]['target_id'] = $hearing->uid;

  $mail_templates = ktc_hearing_generate_mail_templates($hearing, $op, $attendee_roles);

  if ($op == 'approved') {
    $summary_markup = ktc_hearing_generate_hearing_summary_view($hearing);
    if (!empty($summary_markup)) {
      // $pdf_attachment = array(
      //   'filepath' => ktc_hearing_generate_pdf($summary_markup),
      //   'filename' => 'høringssvar.pdf',
      //   'filemime' => 'application/pdf',
      // );

      // $params['attachments'][] = $pdf_attachment;

      $plain_attachment = array(
        'filepath' => ktc_hearing_generate_markdown($summary_markup),
        'filename' => 'høringssvar.txt',
        'filemime' => 'text/plain',
      );

      $params['attachments'][] = $plain_attachment;
    }
  }
  $notified_uids = array();

  if (isset($users)) {
    foreach ($users as $role => $role_users) {

      if (isset($mail_templates[$role])) {
        foreach ($role_users as $_user) {
          $user = user_load($_user['target_id']);

          // Skip user if he is already notified for this hearing.
          if (isset($notified_uids[$user->uid])) {
            continue;
          }

          $token_data = array('user' => $user, 'node' => $hearing);
          $to = $user->mail;

          // Testing.
          if ($test_mail = variable_get('ktc_test_mail_address', FALSE)) {
            $to = $test_mail;
          }
          $language = $user->language;

          $params['subject'] = token_replace($mail_templates[$role]['subject'], $token_data);
          $params['body'] = token_replace($mail_templates[$role]['body'], $token_data);

          drupal_mail('ktc_hearing', 'notify_new', $to, $language, $params);

          $notified_uids[$user->uid] = $user->uid;
        }
      }
    }
  }
}

/**
 * Notify single user, as attendee on hearing.
 */
function ktc_hearing_notifications_notify_attendee($uid, $hearing) {
  $role = 'attendees';
  $mail_templates = ktc_hearing_generate_mail_templates($hearing, 'new_hearing', array($role));
  $user = user_load($uid);

  $to = $user->mail;

  // Testing.
  if ($test_mail = variable_get('ktc_test_mail_address', FALSE)) {
    $to = $test_mail;
  }

  $token_data = array('user' => $user, 'node' => $hearing);
  $language = $user->language;

  $params['subject'] = token_replace($mail_templates[$role]['subject'], $token_data);
  $params['body'] = token_replace($mail_templates[$role]['body'], $token_data);

  drupal_mail('ktc_hearing', 'notify_new', $to, $language, $params);
}

/**
 * Generate mail templates for the different roles.
 */
function ktc_hearing_generate_mail_templates($hearing, $op, $attendee_roles) {
  $templates = array();

  $values = variable_get('ktc_hearing_notification_settings', array());

  if (!empty($values)) {
    foreach ($attendee_roles as $role) {
      if ($mail = node_load($values[$role][$op])) {

        $subject_field = field_get_items('node', $mail, 'field_subject');
        $body = field_get_items('node', $mail, 'body');

        if ($subject_field && $body) {
          $templates[$role] = array(
            'subject' => $subject_field[0]['value'],
            'body' => $body[0]['value'],
          );
        }
      }
    }
  }

  return $templates;
}
