<?php
/**
 * @file
 * Code for the KTC autocomplete module.
 */

/**
 * Implements hook_form_ID_alter().
 */
function ktc_autocomplete_form_og_ui_add_users_alter(&$form, &$form_state, $form_id) {
  $form['og_user']['name']['#title'] = t('Bruger');
  $form['og_user']['name']['#autocomplete_path'] = 'ktc_autocomplete/user/user/name';
}
/**
 * Implements hook_form_ID_alter().
 */
function ktc_autocomplete_form__og_invite_form_alter(&$form, &$form_state, $form_id) {

  $form['invitee']['#autocomplete_path'] = 'ktc_autocomplete/user/user/name';
  $form['#validate'][0] = 'ktc_autocomplete_form_og_invite_form_validte';
  $form['#submit'][0] = 'ktc_autocomplete_form_og_invite_form_submit';
}
/**
 * Implements hook_menu().
 */
function ktc_autocomplete_menu() {
  $items['ktc_autocomplete/%/%/%'] = array(
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'page arguments' => array(1,2,3,4),
    'page callback' => 'ktc_autocomplete_autocomplete',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Override _og_invite_form_validate().
 */
function ktc_autocomplete_form_og_invite_form_validte($form, &$form_state) {
  global $user;

  $group_type = $form_state['values']['group_type'];
  $gid = $form_state['values']['gid'];
  $invitees = explode(',', str_replace(', ', ',', $form_state['values']['invitee']));

  $unrelated = array();
  $unexisting = array();
  $in_group = array();
  $good = array();
  foreach ($invitees as $invitee) {
    if (empty($invitee)) {
      continue;
    }

    $invitee_obj = user_load_by_name($invitee);
    $name = $invitee_obj->name;
    $uid = $invitee_obj->uid;
    // Check if the user exists.
    $exists = db_select('users', 'u')
      ->fields('u', array('uid'))
      ->condition('uid', $uid)
      ->execute()
      ->fetchField();
    if (empty($exists)) {
      $unexisting[] = check_plain($name);
    }
    // If the user exist and if needed check
    // if it is related to the current user.
    elseif (module_exists('user_relationships') && !og_user_access($group_type, $gid, 'invite any user')) {
      $related = db_select('user_relationships', 'ur')
        ->fields('ur', array('rid'))
        ->condition('ur.approved', 1)
        ->condition('ur.requester_id', $user->uid)
        ->condition('ur.requestee_id', $uid)
        ->execute()
        ->fetchField();
      if (empty($related)) {
        $unrelated[] = check_plain($name);
      }
      else {
        $exists_in_group = db_select('og_membership', 'og')
          ->fields('og', array('gid'))
          ->condition('etid', $uid)
          ->condition('entity_type', 'user')
          ->condition('gid', $gid)
          ->execute()
          ->fetchField();
        if (empty($exists_in_group)) {
          $good[] = $invitee;
        }
      }
    }
    // If the user exists and no relation check is needed.
    else {
      $exists_in_group = db_select('og_membership', 'og')
        ->fields('og', array('gid'))
        ->condition('etid', $uid)
        ->condition('entity_type', 'user')
        ->condition('gid', $gid)
        ->execute()
        ->fetchField();
      if (empty($exists_in_group)) {
        $good[] = $invitee;
      }
    }
  }

  // Only keep existing and related users.
  $form_state['values']['invitee'] = implode(',', $good);

  // Display error messages for unexisting and unrelated users.
  if (!empty($unexisting)) {
    drupal_set_message(t('The following users do not exist.'), 'warning');
  }
  if (!empty($unrelated)) {
    drupal_set_message(t('You cannot invite the following users because they are not in relation with you:')
      . ' ' . implode(', ', $unrelated), 'warning');
  }
  if (!empty($exists_in_group)) {
    drupal_set_message(t('You cannot invite the following users because they are already invited or a member.'), 'warning');
  }
}
/**
 * Override _og_invite_form_submit().
 */
function ktc_autocomplete_form_og_invite_form_submit($form, &$form_state) {
  $group_type = $form_state['values']['group_type'];
  $gid = $form_state['values']['gid'];
  $message = check_plain($form_state['values']['message']);
  $invitees = explode(',', str_replace(', ', ',', $form_state['values']['invitee']));

  $entity = entity_load_single($group_type, $gid);
  $label = entity_label($group_type, $entity);
  $field_name = key(og_get_group_audience_fields());
  foreach ($invitees as $invitee) {
    if (empty($invitee)) {
      continue;
    }
    $invitee_obj = user_load_by_name($invitee);
    $name = ($field = field_get_items('user', $invitee_obj, 'field_navn')) ?
            $field[0]['value'] : $invitee_obj->name;
    $uid = $invitee_obj->uid;
    $result = og_invite_invite($group_type, $gid, $field_name, $uid, $message);

    if (!empty($result)) {
      drupal_set_message(t('<em>@user</em> has been invited to the group <em>@label</em>.', array('@user' => $name, '@label' => $label)));
    }
    else {
      drupal_set_message(t('An error happened while inviting <em>@user</em> to the group <em>@label</em>', array('@user' => $name, '@label' => $label)), 'error');
    }
  }
}
/**
 * KTC autocomplete path callback function.
 *
 * @param entity $reference_type
 *   entity type
 * @param string $bundle
 *   bundle in db
 * @param string $key_field
 *   the field that is returned to the form on submission
 * @param string $string
 *   the string to search for
 */
function ktc_autocomplete_autocomplete($reference_type, $bundle, $key_field, $string) {
  $string = db_like($string);

  $limit = 0;

  switch ('contains') {
    case 'begins_with':
      $string = $string . '%';
      break;

    case 'contains':
      $string = '%' . $string . '%';
      break;

  }

  switch ($reference_type) {
    case 'user':
      // TODO : move these two lists to an admin config form,
      // to make them configurable on an entity_type-bundle basis.
      $search_fields = array('field_navn', 'mail', 'field_employer_name');
      $show_fields = array('field_navn', 'field_employer_name');
      // $show_fields = '[user:field_navn]';

      $join = '';
      $where = '(0';
      $concat = array();
      foreach ($search_fields as $field) {
        if (in_array($field, array('name', 'mail'))) {
          $where .= ' or ' . db_escape_field($field) . ' like \'' . $string . '\'';
        }
        else {
          // TODO : this works for fields having 'value'
          // column only - check field type here.
          $join .= ' left join field_data_' . db_escape_table($field) . ' on field_data_' . db_escape_field($field) . '.entity_id=uid and field_data_' . db_escape_table($field) . '.entity_type=\'user\'';
          $where .= ' or field_data_' . db_escape_table($field) . '.' . db_escape_field($field) . '_value like \'' . $string . '\'';

        }
      }

      $where .= ')';

      if (is_array($show_fields)) {
        foreach ($show_fields as $field) {
          if (in_array($field, array('name', 'mail'))) {
            $concat[] = $field;
          }
          else {
            $concat[] = 'field_data_' . db_escape_table($field) . '.' . db_escape_field($field) . '_value';
          }
        }
        $sql = 'select users.uid as id, ' . db_escape_field($key_field) . ' as k, concat_ws(\',  \', ' . implode(',', $concat) . ') as title from users ' . $join . ' where ' . $where;
      }
      else {
        $sql = 'select users.uid as id, ' . db_escape_field($key_field) . ' as k from users ' . $join . ' where ' . $where;
      }

      if ($limit > 0) {
        $sql .= ' limit ' . $limit;
      }

      // $sql = 'select concat(name, \' [uid:\', uid, \']\') as id,
      // concat(' . implode(',\' - \',', $concat) . ')
      // as title from users ' . $join . ' where ' . $where . ' limit ' . $limit;
      // {"lars [uid:6]":"\u003Cdiv class=\u0022reference-autocomplete\u0022\u003Elars\u003C\/div\u003E"}

      break;

    case 'node':
      $result = db_query('select nid as id, title as title from node where title like :q', array(':q' => $string . '%'));
      break;

  }

  try {
    if (isset($_GET['debug'])) {
      print ($sql);
    }
    $result = db_query($sql);
  }
  catch(Exception $e) {
    $result = array();
    die($sql . ' - ' . $e);
  }

  $items = array();
  foreach ($result as $obj) {

    if (is_array($show_fields)) {
      $title = $obj->title;
    }
    else {
      $entities = entity_load($reference_type, array($obj->id));
      $entity = $entities[$obj->id];
      $data = array($reference_type => $entity);
      $title = token_replace($show_fields, $data);

    }
    if (!trim($title)) {
      $title = $obj->k;
    }

    $items[$obj->k] = check_plain($title);

  }

  drupal_json_output($items);
  exit();
}
