<?php
/**
 * @file
 * KTC Users signup module.
 */

/**
 * Implements hook_menu().
 */
function ktc_users_signup_menu() {
  $items['user/signup'] = array(
    'title' => 'Opret bruger',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_users_signup_form'),
    'access callback' => TRUE,
  );

  $items['admin/config/people/ktc_users_signup'] = array(
    'title' => 'KTC Opret bruger',
    'description' => 'Indstillinger for KTC opret bruger',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_users_signup_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function ktc_users_signup_init() {
  if (arg(0) == 'user' && arg(1) == 'reset') {
    $account = user_load(arg(2));

    if (!$account->access) {
      drupal_set_title('Velkommen til ' . variable_get('site_name', ''));
    }
  }
}

/**
 * Settings for ktc users signup.
 */
function ktc_users_signup_settings_form() {
  $form['ktc_users_signup_preface'] = array(
    '#type' => 'textarea',
    '#title' => t('Forord'),
    '#default_value' => variable_get('ktc_users_signup_preface', ''),
  );

  $form['ktc_users_signup_pre_usertype'] = array(
    '#type' => 'textarea',
    '#title' => t('Før brugertyper'),
    '#default_value' => variable_get('ktc_users_signup_pre_usertype', ''),
  );

  $form['ktc_users_signup_suffix'] = array(
    '#type' => 'textarea',
    '#title' => t('Efterord'),
    '#default_value' => variable_get('ktc_users_signup_suffix', ''),
  );

  $form['ktc_users_signup_completed'] = array(
    '#type' => 'textarea',
    '#title' => t('Bruger oprettet'),
    '#default_value' => variable_get('ktc_users_signup_completed', ''),
  );

  return system_settings_form($form);
}

/**
 * Signup form.
 */
function ktc_users_signup_form($form, &$form_state) {
  if (arg(2) == 'no') {
    drupal_set_message(t('Det er ikke muligt at oprette dig som bruger med den angivne e-mailadresse. Anvend en anden e-mailadresse, eller kontakt KTC Sekretariatet for hjælp'), 'error');
    drupal_goto('user/signup');
  }

  if (isset($form_state['#existing_contact'])) {
    $contact = $form_state['#existing_contact'];
    $firma = '';

    if (isset($contact['field_account'])) {
      $account = taxonomy_term_load($contact['field_account'][LANGUAGE_NONE][0]['tid']);
      $firma = $account->name;
    }

    $form['existing_user'] = array(
      '#type' => 'item',
      '#title' => 'Vi har fundet en eksisterende person med din e-mailadresse<br /><br />',
      '#markup' => '<p><b>Navn:</b> ' . $contact['field_navn'][LANGUAGE_NONE][0]['value'] . ' ' . $contact['field_efternavn'][LANGUAGE_NONE][0]['value'] . '</p><p><b>Firma:</b> ' . $firma . '</p><p><b>E-mail:</b> ' . $form_state['values']['mail'] . '</p>',
    );

    $form_state['#create_from_existing'] = TRUE;

    $form['submit'] = array(
      '#prefix' => '<br /><br /><p><b>Er du denne person - og vil du fortsætte med at oprette/aktivere brugeren på www.ktc.dk?</b></p>',
      '#value' => 'Ja, opret',
      '#type' => 'submit',
      '#suffix' => l(t('Nej, annuller'), 'user/signup/no'),
    );
    return $form;
  }

  global $user;
  if ($user->uid) {
    drupal_goto('user');
  }

  if ($form_state['rebuild']) {
    $form['completed'] = array(
      '#type' => 'item',
      '#markup' => variable_get('ktc_users_signup_completed', ''),
    );
    return $form;
  }

  $usertype_vocab = taxonomy_vocabulary_machine_name_load('brugertyper');

  $usertypes = taxonomy_term_load_multiple(array(), array('vid' => $usertype_vocab->vid));

  $usertype_options = array();

  foreach ($usertypes as $usertype) {
    $usertype_options[$usertype->tid] = array(
      $usertype->name,
      $usertype->description,
    );
  }

  $form['preface'] = array(
    '#type' => 'item',
    '#markup' => variable_get('ktc_users_signup_preface', ''),
  );

  $form['firstname'] = array(
    '#title' => t('Fornavn'),
    '#required' => TRUE,
    '#type' => 'textfield',
  );

  $form['lastname'] = array(
    '#title' => t('Efternavn'),
    '#required' => TRUE,
    '#type' => 'textfield',
  );

  $form['mail'] = array(
    '#title' => t('E-mail'),
    '#required' => TRUE,
    '#type' => 'textfield',
  );

  $form['pass'] = array(
    '#title' => t('Adgangkode'),
    '#required' => TRUE,
    '#type' => 'password',
  );

  $form['pass_repeat'] = array(
    '#title' => t('Gentag adgangkode'),
    '#required' => TRUE,
    '#type' => 'password',
  );

  $form['pre_usertype'] = array(
    '#markup' => variable_get('ktc_users_signup_pre_usertype', ''),
    '#required' => TRUE,
    '#type' => 'item',
  );

  $form['usertype'] = array(
    '#header' => array('Brugertype', 'Beskrivelse'),
    '#multiple' => FALSE,
    '#options' => $usertype_options,
    '#type' => 'tableselect',
  );

  $form['suffix'] = array(
    '#type' => 'item',
    '#markup' => variable_get('ktc_users_signup_suffix', ''),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Opret',
  );

  return $form;
}

/**
 * Implements hook_FORM_ID_validate().
 */
function ktc_users_signup_form_validate($form, $form_state) {
  if (isset($form_state['#create_from_existing'])) {
    return;
  }
  if (!$form_state['values']['usertype']) {
    form_set_error('usertype', t('Du skal angive en brugertype.'));
  }

  if ($form_state['values']['pass'] != $form_state['values']['pass_repeat']) {
    form_set_error('pass_repeat', t('De indtastede adgangkoder er ikke ens.'));
  }

  if ($message = user_validate_mail($form_state['values']['mail'])) {
    form_set_error('mail', $message);
  }

  $mail = $form_state['values']['mail'];
  if (db_query("SELECT mail FROM {users} WHERE LOWER(:mail) = LOWER(mail)",
    array(':mail' => $mail))->fetchField()) {
    form_set_error('mail', t('E-mail adressen er allerede i brug, hvis du har glemt din kode, kan du trykke <a href="@link">her</a> for at nulstille den.', array('@link' => '/user/password')));
  }
}

/**
 * Implements hook_FORM_ID_submit().
 */
function ktc_users_signup_form_submit(&$form, &$form_state) {
  $firstname = ucwords(trim(preg_replace('/\s+/',' ', $form_state['values']['firstname'])));
  $lastname = ucwords(trim(preg_replace('/\s+/',' ', $form_state['values']['lastname'])));;
  $mail = $form_state['values']['mail'];
  $pass = $form_state['values']['pass'];
  $usertype = $form_state['values']['usertype'];

  $fields = array(
    'name' => $mail,
    'field_navn' => array(LANGUAGE_NONE => array(array('value' => $firstname))),
    'field_efternavn' => array(LANGUAGE_NONE => array(array('value' => $lastname))),
    'mail' => $mail,
    'pass' => $pass,
    'init' => 'mail address',
    'status' => 1,
    'field_usertype' => array(LANGUAGE_NONE => array(array('tid' => $usertype))),
    'roles' => array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
    ),
  );

  
  // If the form is resubmitted with create_from_existing set, use this data
  // for the new user.
  if (isset($form_state['#create_from_existing'])) {
    $fields = $form_state['#existing_contact'];
    unset($form_state['#create_from_existing']);
    unset($form_state['#existing_contact']);
  }
  else {
    $webuserdto = ktc_crm_lookup_webuser_by_mail($mail);

    // If the return is 'error', break the signup process. We don't want to
    // create users before we can talk to CRM.
    if ($webuserdto == 'error') {
      drupal_set_message(t('Der er sket en teknisk fejl, prøv venligst igen senere.'), 'error');
      drupal_goto('user/signup');
      return;
    }

    // Check to see if there already is a user with this mail address in crm.
    if ($webuserdto) {
      // If so, create the new user from this webuserdto.
      $form_state['#existing_contact'] = array_merge($fields, ktc_crm_map_webuserdto_to_edit_array($webuserdto));
      //user status must be active when he singup
      $form_state['#existing_contact']['status'] = 1;
      $form_state['rebuild'] = TRUE;
      return;
    }
  }

  $account = user_save('', $fields);

  $op = 'register_no_approval_required';
  // Send an email.
  _user_mail_notify($op, $account);

  $form_state['rebuild'] = TRUE;
}

/**
 * Implements hook_user_login().
 */
function ktc_users_user_login(&$edit, $account) {
  global $user;
  $webuserdto = ktc_crm_lookup_webuser_by_mail($account->mail); 
  ktc_crm_update_account_from_webuserdto($webuserdto);
  $webuserdto->LastLogin = date('Y-m-d\TH:i:s', $account->access);
  ktc_crm_update_user($webuserdto);
  if ($account->access == 0) {
    drupal_set_message($user->mail);
    drupal_goto('user/' . $user->uid . '/edit');
  }
}
