<?php

$networks = [
'ERFA for faggruppeformænd',
'ERFA for kredsbestyrelser i KTC-kredse',
'Forsyning projektrum',
'Fælles Kommunalt Geodata Samarbejde',
'KTC Artikler',
'KTC Debat',
'KTC faggruppe for Almene Boliger - ALM',
'KTC faggruppe for Byggelov - BYG',
'KTC faggruppe for digital forvaltning - DFO',
'KTC Faggruppe for klima, energi og ressourcer - KER',
'KTC Faggruppe for Kommunal Ejendomsdrift - EJD',
'KTC faggruppe for Ledelse - LED',
'KTC faggruppe for Miljø og Grundvand - MIG',
'KTC faggruppe for Natur- og overfladevand - NOV',
'KTC faggruppe for planlægning - PLAN',
'KTC faggruppe Veje, Trafik- og Trafiksikkerhed - VTT',
'KTC Filarkiv',
'KTC hovedbestyrelse',
'KTC Hovedstaden - kredsbestyrelse',
'KTC Hovedstaden - medlemmer',
'KTC i pressen',
'KTC Jobmesse - Lyngby 9. og 10. april 2014',
'KTC jobmesse Aalborg 2014',
'KTC medlemsnetværk',
'KTC Midtjylland - kredsbestyrelse',
'KTC Midtjylland - medlemmer',
'KTC Nordjylland - Kredsbestyrelse',
'KTC Nordjylland - medlemmer',
'KTC Nyt om navne',
'KTC Sekretariat netværk',
'KTC Sjælland - Kredsbestyrelse',
'KTC Sjælland - medlemmer',
'KTC Syddanmark - Kredsbestyrelse',
'KTC underfaggruppe DFO - BBR drift',
'KTC Underfaggruppe DFO - BBR udvikling',
'KTC underfaggruppe DFO - Ejendomme',
'KTC underfaggruppe DFO - FOSAKO-FU',
'KTC underfaggruppe KER - Affald/ressourcer',
'KTC underfaggruppe MIG - landbrug',
'KTC underfaggruppe MIG - råstoffer',
'KTC underfaggruppe MIG - virksomheder',
'KTC underfaggruppe NOV - Klimatilpasning',
'KTC underfaggruppe NOV - Natur',
'KTC underfaggruppe NOV - Overfladevand',
'KTC underfaggruppe NOV - Spildevand',
'KTC underfaggruppe VTT - Det rådgivende cykeludvalg',
'KTC underfagruppe KER - Klimastrategi og grøn omstilling',
'KTC Årsmøde 2012 - Spor 6',
'Seniornetværk i KTC',
'sssssssssssssss',
'Test BC faggruppe 01',
'Test BC faggruppe 02',
'Test BC foreningsnetværk',
'Test BC kredsnetværk 01',
'Test BC KTC internt netværk 01',
'Testnetværk m høringer',
'Testnetværk m høringer',
'Testnetværk m høringer',
'Æbler / bananer',
  ];

foreach ($networks as $network) {
  $condition = ['title' => $network];
  $group = reset(node_load_multiple([],$condition));
  if ($group && $group->type == 'group') {
    echo $group->title."\n";
    og_membership_delete_by_group('node', $group);
  }
}
