<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

define('KTC_NETVEARK_COMMENT_NOTIFY_DEFAULT_SUBJECT', 'Ny kommentar i netværket [node:og-group-ref]');
define('KTC_NETVEARK_COMMENT_NOTIFY_DEFAULT_MAILTEXT', 'Hej [user:field_navn]

Der er en ny kommentar i netværket: <a href="[node:ktc-netvaerk-url]">[node:og-group-ref]</a> som du er medlem af:
Kommentar til: <a href="[node:url]">[comment:node:title]</a>
Af: [comment:author]

Kommentar:

[comment:body]

Se hele dialogen her: [comment:url]

Har du spørgsmål til brugen af KTC Netværk og ktc.dk, kan du søge viden på http://www.ktc.dk/om-ktc/hjaelp, eller kontakte supporten i KTC Sekretariatet: support@ktc.dk, eller pr. telefon +45 7228 2804');


define('KTC_NETVEARK_COMMENT_NOTIFY_AUTHOR_SUBJECT', 'Du har fået en kommentar på dit indlæg: [comment:node:title]');
define('KTC_NETVEARK_COMMENT_NOTIFY_AUTHOR_MAILTEXT', 'Hej [comment:node:author],

Du har fået en kommentar på: "[comment:node:title]"

----
[comment:body]
----
Du kan se hele kommentaren på:
[comment:url]

Du kan afmelde notifikationer for nye kommentarer på dit indhold
ved at følge dette link: [comment:node:author:edit-url].

Har du spørgsmål til brugen af KTC Netværk og ktc.dk, kan du søge viden på http://www.ktc.dk/om-ktc/hjaelp, eller kontakte supporten i KTC Sekretariatet: support@ktc.dk, eller pr. telefon +45 7228 2804');

/**
 * Implements hook_permission().
 */
function ktc_netvaerk_comment_notify_permission() {
  return array(
    'administer ktc netvaerk comment notify' => array(
      'title' => 'Administer Comment Notify',
      'description' => 'Change global comment notification settings.',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ktc_netvaerk_comment_notify_menu() {
  $items['admin/netvaerk_setting/comment_notify'] = array(
    'title' => 'Comment Notify',
    'description' => 'Configure settings for e-mails about new comments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_netvaerk_comment_notify_settings'),
    'access arguments' => array('administer ktc netvaerk comment notify'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/*
 * Page callback for administrative settings form.
 */

function ktc_netvaerk_comment_notify_settings() {
  $form['ktc_netvaerk_comment_notify_settings'] = array();

  $form['ktc_netvaerk_comment_notify_settings']['ktc_netvaerk_comment_notify_default_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Emne'),
    '#return_value' => 1,
    '#token_types' => array('comment', 'user', 'node'),
    '#default_value' => variable_get('ktc_netvaerk_comment_notify_default_subject', KTC_NETVEARK_COMMENT_NOTIFY_DEFAULT_SUBJECT),
    '#element_validate' => array('token_element_validate'),
  );
    $mailtext = variable_get('ktc_netvaerk_comment_notify_default_mailtext', array('value' => KTC_NETVEARK_COMMENT_NOTIFY_DEFAULT_MAILTEXT));
    $form['ktc_netvaerk_comment_notify_settings']['ktc_netvaerk_comment_notify_default_mailtext'] = array(
    '#type'=>'text_format',
    '#format'=>'filtered_html',
    '#title' =>  t('Notifikation om ny kommentar i netværk'),
    '#default_value' => $mailtext['value'],
    '#return_value' => 1,
    '#cols' => 80,
    '#rows' => 15,
    '#token_types' => array('comment', 'user', 'node'),
    '#element_validate' => array('token_element_validate'),
  );
  ;
  $form['ktc_netvaerk_comment_notify_settings']['ktc_netvaerk_comment_notify_author_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Emne'),
    '#return_value' => 1,
    '#token_types' => array('comment', 'user', 'node'),
    '#default_value' => variable_get('ktc_netvaerk_comment_notify_author_subject', KTC_NETVEARK_COMMENT_NOTIFY_AUTHOR_SUBJECT),
    '#element_validate' => array('token_element_validate'),
  );

  $mailtext = variable_get('ktc_netvaerk_comment_author_default_mailtext', array('value' => KTC_NETVEARK_COMMENT_NOTIFY_AUTHOR_MAILTEXT));
  $form['ktc_netvaerk_comment_notify_settings']['ktc_netvaerk_comment_author_default_mailtext'] = array(
    '#type'=>'text_format',
    '#format'=>'filtered_html',
    '#title' =>  t('Default mail text for sending out the notifications to node authors'),
    '#default_value' => $mailtext['value'],
    '#return_value' => 1,
    '#cols' => 80,
    '#rows' => 15,
    '#token_types' => array('comment', 'user', 'node'),
    '#element_validate' => array('token_element_validate'),
  );

  $form['ktc_netvaerk_comment_notify_settings']['token_help'] = array(
    '#theme' => 'token_tree',
    '#token_types' => array('comment', 'user', 'node'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_node_insert().
 */
function ktc_netvaerk_comment_notify_comment_insert($comment) {
  $node = node_load($comment->nid);
  if (is_object($node) && $node->status && $field = field_get_items('node', $node, 'og_group_ref')) {
    $field = reset($field);
    $group_id = $field['target_id'];
    //not send notification if network is unpublished
    if (_ktc_netvaerk_comment_notify_get_node_status($group_id) === "0") {
      return;
    }
    ktc_netvaerk_comment_notify_send_notification_emails($comment);
  }
  else {
    $user = user_load($node->uid);
    ktc_netvaerk_comment_notify_send_mail('notify_author', $comment, $user, $node);
  }
}

function ktc_netvaerk_comment_notify_send_notification_emails($comment) {
  $result = db_query('SELECT status FROM {ktc_netvaerk_comment_notify} WHERE nid = :nid AND cid = :cid AND status = :status', array(':nid' => $comment->nid, ':cid' => $comment->cid, ':status' => 1))->fetchAll();
  $node = node_load($comment->nid);
  if (empty($result)) {
    $fields = field_get_items('node', $node, 'og_group_ref');
    $uids = array();
    $groups = array();
    foreach ($fields as $field) {
      $group_id = $field['target_id'];
      $uids= array_merge($uids,  _ktc_netvaerk_notifications_get_users($group_id));
      $groups[] = $group_id;
    }

    $uids = array_unique($uids);
    foreach ($uids as $uid) {
      $user = user_load($uid);
      $send_notification = FALSE;
      foreach ( $groups as $group_id) {
        if (og_is_member('node', $group_id, 'user', $user)) {
          $send_notification = TRUE;
          break;
        }
      }
      if ($send_notification === FALSE) continue;
      ktc_netvaerk_comment_notify_send_mail('notify_default',  $comment, $user, $node);
    }
    db_insert('ktc_netvaerk_comment_notify')
        ->fields(array(
          'nid' => $comment->nid,
          'cid' => $comment->cid,
          'status' => 1,
        ))
        ->execute();
  }
}

function ktc_netvaerk_comment_notify_send_mail($notification_type, $comment, $user, $node) {
  $token_data = array('user' => $user, 'comment' => $comment, 'node' => $node);
  $to = $user->mail;

  // Testing.
  if ($test_mail = variable_get('ktc_test_mail_address', FALSE)) {
    $to = $test_mail;
  }
  $language = $user->language;

  $params = array();
  if ($notification_type  == 'notify_author') {
    $body = $mailtext['value'] = variable_get('ktc_netvaerk_comment_author_default_mailtext', array('value' => KTC_NETVEARK_COMMENT_NOTIFY_AUTHOR_MAILTEXT));
    $params['subject'] = token_replace(variable_get('ktc_netvaerk_comment_notify_author_subject', KTC_NETVEARK_COMMENT_NOTIFY_AUTHOR_SUBJECT), $token_data);
    $params['body'] = token_replace($body['value'], $token_data);

  }
  else {
    $body = $mailtext['value'] = variable_get('ktc_netvaerk_comment_notify_default_mailtext', array('value' => KTC_NETVEARK_COMMENT_NOTIFY_DEFAULT_MAILTEXT));
    $params['subject'] = token_replace(variable_get('ktc_netvaerk_comment_notify_default_subject', KTC_NETVEARK_COMMENT_NOTIFY_DEFAULT_SUBJECT), $token_data);
    $params['body'] = token_replace($body['value'], $token_data);

  }
    drupal_mail('ktc_netvaerk_comment_notify', 'notify_new', $to, $language, $params);
  error_log('mail sent:' . $to);
}

/**
 * Implements hook_mail().
 */
function ktc_netvaerk_comment_notify_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}

/**
 * Implements hook_form_alter().
 */
function ktc_netvaerk_comment_notify_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    // Unset groups the user is not member of.
    // Get the users groups.
    $options = og_get_groups_by_user($form['#entity'], 'node');

    if (empty($options)) {
     $form['field_netvaerk_comment_notify']['#access'] = FALSE;
    }

  // Get the current selected options. We don't wan't to unset these.
    $default_value = $form['field_netvaerk_comment_notify'][LANGUAGE_NONE]['#default_value'];
    foreach ($default_value as $_val) {
      $options[$_val] = $_val;
    }

    // The actual unsetting.
    foreach ($form['field_netvaerk_comment_notify'][LANGUAGE_NONE]['#options'] as $gid => $value) {
      //// hide notification settings if network unpublished
      if (_ktc_netvaerk_comment_notify_get_node_status($gid) === "0") {
        unset($form['field_netvaerk_comment_notify'][LANGUAGE_NONE]['#options'][$gid]);
      }
      if (!is_array($options) || !in_array($gid, $options)) {
        unset($form['field_netvaerk_comment_notify'][LANGUAGE_NONE]['#options'][$gid]);
      }
      // hide notification settings if user is not member of network
      if (!og_is_member('node', $gid, 'user', $form['#entity'])) {
        unset($form['field_netvaerk_comment_notify'][LANGUAGE_NONE]['#options'][$gid]);
      }
    }
  }
}

function _ktc_netvaerk_comment_notify_get_users($group_id) {

  // Get a list of users who want notifications for this group.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'user')
      ->fieldCondition('field_netvaerk_comment_notify', 'target_id', $group_id);
  $result = $query->execute();

  if (isset($result['user'])) {
    return array_keys($result['user']);
  }
  return array();
}
/**
 * Helper function to get the node status.
 */
function _ktc_netvaerk_comment_notify_get_node_status($nid) {
  return db_query('SELECT status FROM {node} WHERE nid = :nid', array(':nid' => $nid))->fetchField();
}