<?php
/**
 * @file
 * Code for the KTC content types feature.
 */

include_once 'ktc_content_types.features.inc';

function ktc_content_types_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['listevisning'] = array(
    'label' => t('Listevisning'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['listevisningstor'] = array(
    'label' => t('Listevisning Stor'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['listevisningboks'] = array(
    'label' => t('Listevisning boks'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['teasercomments'] = array(
    'label' => t('Teaser with comments'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ktc_content_types_form_node_form_alter(&$form, $form_state, $form_id) {
  // Properly hide hidden groups.
  ktc_content_types_field_group_hide_field_groups($form, array('group_hidden'));

  // Remove n/a from radio.
  unset($form['field_hearing_official'][LANGUAGE_NONE]['#options']['_none']);

  // Fetch info about managed vocabularies.
  $manage_vocabularies = ktc_content_types_manage_vocabularies();

  // Iterate through and enforce user access.
  foreach ($manage_vocabularies as $vocabulary_name => $data) {
    $field = $data['field'];
    $perm = $data['perm'];
    if (isset($form[$field])) {
      if (!user_access($perm . 'all')) {
        foreach ($form[$field]['und']['#options'] as $tid => $label) {
          if (!user_access($perm . $tid)) {
            unset($form[$field][LANGUAGE_NONE]['#options'][$tid]);
          }
        }
      }
    }
  }
}

/**
 * Hides field groups including children in a render array.
 *
 * @param array $element
 *   A render array. Can be a form, node, user, ...
 * @param array $group_names
 *   An array of field group names that should be hidden.
 */
function ktc_content_types_field_group_hide_field_groups(&$element, $group_names) {
  foreach ($group_names as $group_name) {
    if (isset($element['#fieldgroups'][$group_name]) && isset($element['#group_children'])) {
      // Hide the field group.
      $element['#fieldgroups'][$group_name]->format_type = 'hidden';
      // Hide the elements inside the field group.
      foreach (array_keys($element['#group_children'], $group_name) as $field_name) {
        $element[$field_name]['#access'] = FALSE;
      }
    }
  }
}

/**
 * Vocabularies we manage access for.
 */
function ktc_content_types_manage_vocabularies() {
  // This array holds the taxonomy vocabulary names on the vocabularies
  // we want to manage access for.
  return array(
    'os2web_news_page_newstypes' => array(
      'title' => 'Brug nyhedstype: ',
      'perm' => 'use newstype-',
      'field' => 'field_os2web_news_page_type',
    ),
    'os2web_base_tax_promoteto' => array(
      'title' => 'Forfrem til: ',
      'perm' => 'promote to-',
      'field' => 'field_os2web_base_field_promote',
    ),
    'arrangementstyper' => array(
      'title' => 'Brug arrangementstype: ',
      'perm' => 'use activitytype-',
      'field' => 'field_arrangement_type',
    ),
    'artikeltyper' => array(
      'title' => 'Brug artikeltype: ',
      'perm' => 'use articletype-',
      'field' => 'field_artikeltype',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function ktc_content_types_permission() {
  $vocabularies = ktc_content_types_manage_vocabularies();

  foreach ($vocabularies as $vocabulary_name => $data) {
    $vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_name);
    $terms = taxonomy_get_tree($vocabulary->vid, 0, 1);

    $permissions[$data['perm'] . 'all'] = array(
      'title' => $data['title'] . 'Alle',
    );

    foreach ($terms as $key => $term) {
      $permissions[$data['perm'] . $term->tid] = array(
        'title' => $data['title'] . $term->name,
      );
    }
  }

  return $permissions;
}

/**
 * Publish/unpublish node form.
 */
function ktc_content_types_publish_node_form($form, $form_state, $nid, $status) {
  $new_status = $status == 'publish' ? 1 : 0;

  $form['status'] = array(
    '#type' => 'value',
    '#value' => $new_status,
  );

  $form['nid'] = array(
    '#type' => 'value',
    '#value' => $nid,
  );

  if ($new_status) {
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Udgiv',
      '#attributes' => array('class' => array('btn-success')),
    );
  }
  else {
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Træk tilbage',
      '#attributes' => array('class' => array('btn-warning')),
    );
  }

  return $form;
}

/**
 * Submit handler, publish/unpublish node.
 */
function ktc_content_types_publish_node_form_submit(&$form, &$form_state) {
  if ($node = node_load($form_state['values']['nid'])) {
    $node->status = $form_state['values']['status'];

    node_save($node);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function ktc_content_types_preprocess_page(&$variables) {
  if (isset($variables['node']) && is_object($variables['node'])) {
    global $user;

    if ($variables['node']->uid == $user->uid) {
      if ($variables['node']->status) {
        $output = drupal_render(drupal_get_form('ktc_content_types_publish_node_form', $variables['node']->nid, 'unpublish'));
      }
      else {
        $output = '<div class="alert alert-danger" role="alert">';
        $output .= 'Denne side er kun gemt som kladde, og er skjult for alle andre. Du kan redigere indholdet ved at klikke på rediger, eller udgive indholdet ved at klikke på Udgiv.';
        $output .= drupal_render(drupal_get_form('ktc_content_types_publish_node_form', $variables['node']->nid, 'publish'));
        $output .= '</div>';
      }

      $variables['node_publish'] = array(
        '#markup' => $output,
      );
    }
  }
}
