<?php
/**
 * @file
 * Code for the KTC content types feature.
 */

include_once 'ktc_content_types.features.inc';

function ktc_content_types_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['listevisning'] = array(
    'label' => t('Listevisning'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['listevisningstor'] = array(
    'label' => t('Listevisning Stor'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['teasercomments'] = array(
    'label' => t('Teaser with comments'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_alter().
 */
function ktc_content_types_form_alter(&$form, &$form_state, $form_id) {
  // On node comment forms, hide the notify settings. Don't allow the user
  // to decide wether og not to recieve notifications.
  if (strstr($form_id, 'comment_node_')) {
    unset($form['notify_settings']);
  }
}
