<?php
/**
 * @file
 * KTC Users roles module.
 */

/**
 * Implements hook_menu().
 */
function ktc_users_roles_menu() {
  $items['admin/people/permissions/ktc_users_roles'] = array(
    'title' => 'KTC Brugere - gruppetype -> rolle',
    'descripiton' => '',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer user permissions'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_users_roles_group_page'),
  );

  $items['admin/people/permissions/ktc_usertype_roles'] = array(
    'title' => 'KTC Brugere - brugertype -> rolle',
    'descripiton' => '',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer user permissions'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_users_roles_usertype_page'),
  );

  $items['admin/people/permissions/ktc_grouproles'] = array(
    'title' => 'KTC Brugere - Netværksroller',
    'descripiton' => '',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer user permissions'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_users_grouproles_page'),
  );
  return $items;
}

/**
 * Implements hook_user_presave().
 */
function ktc_users_roles_user_presave(&$edit, $account, $category) {
  $usertype_map = variable_get('ktc_users_roles_usertype_map', array());

  $edit_new_usertype = FALSE;
  if (!empty($edit['field_usertype']) && $edit['field_usertype'][LANGUAGE_NONE][0]['tid']) {
    $edit_new_usertype = $edit['field_usertype'][LANGUAGE_NONE][0]['tid'];
  }

  $account_old_usertype = FALSE;
  if (!empty($account->field_usertype) && $account->field_usertype[LANGUAGE_NONE][0]['tid']) {
    $account_old_usertype = $account->field_usertype[LANGUAGE_NONE][0]['tid'];
  }

  // If a usertype was set, and a role rule is set for it. We want to remove it
  // from the user.
  if ($account_old_usertype && $usertype_map[$account_old_usertype]) {
    $role_id = $usertype_map[$account_old_usertype];
    // Remove the role.
    $edit['roles'][$role_id] = 0;
  }

  // If a new usertype is set, and a role rule is set for it. The new role
  // should be added to the user.
  if ($edit_new_usertype && $usertype_map[$edit_new_usertype]) {
    $role_id = $usertype_map[$edit_new_usertype];
    // Add the role.
    $edit['roles'][$role_id] = $role_id;
  }
}

/**
 * Page callback for grouproles settings.
 */
function ktc_users_grouproles_page() {
  $form['info'] = array(
    '#type' => 'item',
    '#title' => 'Beskrivelse -> Grupperoller',
    '#markup' => 'Den rolle der sættes på et gruppe/udvalgsmedlemsskab i CRM, kan oversættes til en grupperolle i netværket i Drupal.<br /> Således kan en "Formand" i CRM få en drupal specifik rolle når hans gruppe/udvalgsmedlemskab synkroniseres.',
  );

  // Save settings in an array.
  $form['ktc_users_grouproles_map'] = array(
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#title' => t('Her skal du vælge hvilken af de ovenfor valgte roller, CRM rollen skal oversættes til.'),
  );

  $grouproles_vocab = taxonomy_vocabulary_machine_name_load('ktc_netvaerk_grouproles');
  $grouproles = taxonomy_term_load_multiple(array(), array('vid' => $grouproles_vocab->vid));

  $grouprole_map = variable_get('ktc_users_grouproles_map', array());

  // Available OG roles. Unset 'non-member' and 'member' as they are irrelevant
  // for this.
  $og_roles = og_roles('node', 'group');
  unset($og_roles[1]);
  unset($og_roles[2]);

  $og_roles[0] = t('- None -');

  foreach ($grouproles as $grouprole) {
    $grid = $grouprole->tid;
    $form['ktc_users_grouproles_map'][$grid] = array(
      '#title' => $grouprole->name,
      '#type' => 'select',
      '#options' => $og_roles,
      '#default_value' => isset($grouprole_map[$grid]) ? $grouprole_map[$grid] : 0,
    );
  }

  return system_settings_form($form);
}

/**
 * Page callback for usertype settings.
 */
function ktc_users_roles_usertype_page() {
  $form = array();

  $usertype_vocab = taxonomy_vocabulary_machine_name_load('brugertyper');
  $usertypes = taxonomy_term_load_multiple(array(), array('vid' => $usertype_vocab->vid));

  $drupal_role_options = user_roles();
  $drupal_role_options[0] = t('Ingen');

  $form['prefix'] = array(
    '#type' => 'item',
    '#prefix' => t('I kolonnen til venstre står de taksonomi ord der findes i ordforrådet %vocab
       I kolonnen til højre kan der vælges hvilken rolle brugere af denne type skal have.',
      array(
        '%vocab' => $usertype_vocab->name,
      )
    ),
  );

  $form['ktc_users_roles_usertype_map'] = array(
    '#tree' => TRUE,
  );

  $ktc_users_roles_usertype_map = variable_get('ktc_users_roles_usertype_map', array());

  foreach ($usertypes as $type) {
    $form['ktc_users_roles_usertype_map'][$type->tid] = array(
      '#type' => 'select',
      '#prefix' => '<span style="float:left; width: 15%">' . $type->name . '</span>',
      '#default_value' => !empty($ktc_users_roles_usertype_map) ? $ktc_users_roles_usertype_map[$type->tid] : FALSE,
      '#options' => $drupal_role_options,
    );
  }

  return system_settings_form($form);
}

/**
 * Page callback for settings.
 */
function ktc_users_roles_group_page() {
  $grouptype_vocab = taxonomy_vocabulary_machine_name_load('netv_rkstype');
  $grouptypes = taxonomy_term_load_multiple(array(), array('vid' => $grouptype_vocab->vid));

  $grouptype_options[0] = t('- Ingen -');
  foreach ($grouptypes as $type) {
    $grouptype_options[$type->tid] = $type->name;
  }

  asort($grouptype_options);

  $drupal_role_options = user_roles();
  $drupal_role_options[0] = t('Ingen');

  $form['grouptype'] = array(
    '#title' => t('Gruppetype'),
    '#description' => t('Vælg en gruppetype du vil lave en rolle regel for.'),
    '#type' => 'select',
    '#options' => $grouptype_options,
  );

  $form['select_grouptype'] = array(
    '#value' => t('Vælg'),
    '#type' => 'submit',
    '#submit' => array('ktc_users_roles_select_grouptype'),
  );

  $form['role_map'] = array(
    '#tree' => TRUE,
  );

  $role_map = variable_get('ktc_users_roles_map', array());

  $ktc_users_roles_grouptypes = variable_get('ktc_users_roles_grouptypes', array());

  foreach ($ktc_users_roles_grouptypes as $grouptype_tid) {
    $grouptype = taxonomy_term_load($grouptype_tid);

    $form['role_map'][$grouptype_tid] = array(
      '#type' => 'fieldset',
      '#title' => $grouptype->name,
    );

    $og_roles = og_roles('node', 'group');

    foreach ($og_roles as $og_role_id => $og_role_name) {
      $default_value = 0;
      if (!empty($role_map) && isset($role_map[$grouptype_tid]) && isset ($role_map[$grouptype_tid][$og_role_id])) {
        $default_value = $role_map[$grouptype_tid][$og_role_id];
      }

      $form['role_map'][$grouptype_tid][$og_role_id] = array(
        '#type' => 'select',
        '#prefix' => '<span style="float:left; width: 15%">' . $og_role_name . '</span>',
        '#options' => $drupal_role_options,
        '#default_value' => $default_value,
      );
    }

    $form['role_map'][$grouptype_tid]['select_grouptype'] = array(
      '#value' => t('Fjern'),
      '#type' => 'submit',
      '#grouptype_tid' => $grouptype_tid,
      '#submit' => array('ktc_users_roles_select_grouptype'),
    );
  }

  unset($drupal_role_options[0]);
  $form['ktc_users_roles_never_remove'] = array(
    '#title' => t('Fjern aldrig disse roller.'),
    '#options' => $drupal_role_options,
    '#multiple' => TRUE,
    '#type' => 'checkboxes',
    '#default_value' => variable_get('ktc_users_roles_never_remove', array()),
  );

  $form['submit'] = array(
    '#value' => t('Gem'),
    '#type' => 'submit',
  );

  return $form;
}

/**
 * Add a group to the select groups array.
 */
function ktc_users_roles_select_grouptype(&$form, &$form_state) {
  $ktc_users_roles_grouptypes = variable_get('ktc_users_roles_grouptypes', array());

  if (isset($form_state['clicked_button']['#grouptype_tid'])) {
    $selected_grouptype = $form_state['clicked_button']['#grouptype_tid'];

    unset($ktc_users_roles_grouptypes[$selected_grouptype]);

    // Unset from map aswell.
    $role_map = variable_get('ktc_users_roles_map', array());

    unset($role_map[$selected_grouptype]);

    variable_set('ktc_users_roles_map', $role_map);
  }
  else {
    $selected_grouptype = $form_state['values']['grouptype'];

    if ($selected_grouptype) {
      $ktc_users_roles_grouptypes[$selected_grouptype] = $selected_grouptype;
    }
  }
  variable_set('ktc_users_roles_grouptypes', $ktc_users_roles_grouptypes);
}

/**
 * Submit handler for settings.
 */
function ktc_users_roles_group_page_submit(&$form, &$form_state) {
  $role_map = $form_state['values']['role_map'];
  variable_set('ktc_users_roles_map', $role_map);

  $never_remove = $form_state['values']['ktc_users_roles_never_remove'];
  variable_set('ktc_users_roles_never_remove', $never_remove);

  drupal_set_message(t('Indstillingerne er blevet gemt'));

}

/**
 * Process users accumulated roles according to the assigned group roles.
 */
function ktc_users_roles_process_user($uid) {
  $role_map = variable_get('ktc_users_roles_map', array());

  $user_roles = array();

  foreach ($role_map as $grouptype_tid => $group_role_map) {
    $groups = ktc_users_roles_get_group_nids_by_type($grouptype_tid);

    foreach ($groups as $group_nid) {
      $user_roles = $user_roles + ktc_users_roles_process_user_groups($uid, $group_nid, $group_role_map);
    }
  }

  return $user_roles;
}

/**
 * Process users groups.
 */
function ktc_users_roles_process_user_groups($uid, $group_nid, $group_role_map) {
  $user_roles = array();

  $query = db_select('og_users_roles', 'ogur');
  $query->rightJoin('og_membership', 'ogm', 'ogm.etid = ogur.uid');
  $query->fields('ogm')
    ->fields('ogur')
    ->condition('ogm.gid', $group_nid, '=')
    ->condition('ogm.etid', $uid, '=');
  $result = $query->execute()->fetchAll();

  foreach ($group_role_map as $og_role_id => $drupal_role_id) {
    if (is_numeric($drupal_role_id) && $drupal_role_id) {
      foreach ($result as $current_role_info) {
        if ($current_role_info->rid == $og_role_id) {
          $user_roles[$drupal_role_id] = $drupal_role_id;
        }
      }
    }
  }

  return $user_roles;
}

/**
 * Implements hook_og_membership_presave().
 */
function ktc_users_roles_og_membership_presave($og_membership) {
  // If the grouprole field is set, we check if the value triggers a group
  // role assignment.
  if ($field = field_get_items('og_membership', $og_membership, 'field_grouprole')) {
    $group_role_map = variable_get('ktc_users_grouproles_map', array());
    $grid = $field[0]['target_id'];

    if (isset($group_role_map[$grid]) && $group_role_map[$grid]) {
      $new_rid = $group_role_map[$grid];
    }
  }

  if (is_object($og_membership->original) && $field = field_get_items('og_membership', $og_membership->original, 'field_grouprole')) {
    $group_role_map = variable_get('ktc_users_grouproles_map', array());
    $grid = $field[0]['target_id'];

    if (isset($group_role_map[$grid]) && $group_role_map[$grid]) {
      $old_rid = $group_role_map[$grid];
    }
  }

  if ($old_rid == $new_rid) {
    return;
  }

  og_role_revoke($og_membership->group_type, $og_membership->gid, $og_membership->etid, $old_rid);
  og_role_grant($og_membership->group_type, $og_membership->gid, $og_membership->etid, $new_rid);
}

/**
 * Implements hook_og_role_grant().
 */
function ktc_users_roles_og_role_grant($group_type, $gid, $uid, $rid) {
  $role_map = variable_get('ktc_users_roles_map', array());

  // Determine if the user should be assigned a role, according to the
  // membership of a specified network type.
  $group = node_load($gid);

  if ($field = field_get_items('node', $group, 'field_netvaerkstype')) {
    $grouptype_tid = $field[0]['tid'];

    $group_role_map = $role_map[$grouptype_tid];

    if ($group_role_map[$rid]) {
      ktc_users_roles_role($uid, $group_role_map[$rid], 'grant');
    }
  }
}

/**
 * Implements hook_og_role_revoke().
 */
function ktc_users_roles_og_role_revoke($group_type, $gid, $uid, $rid) {
  $role_map = variable_get('ktc_users_roles_map', array());

  $group = node_load($gid);

  // Determine if the user should be revoked a role, according to the
  // membership of a specified network type.
  if ($field = field_get_items('node', $group, 'field_netvaerkstype')) {
    $grouptype_tid = $field[0]['tid'];

    $group_role_map = $role_map[$grouptype_tid];

    // This is far from optimal, and could probarbly be optimised a bit.
    // Since the user can be member of several groups, that all grant a site
    // wide role, we need to make sure that we do not remove any of the roles
    // that the user is entitled to.
    $all_user_roles = ktc_users_roles_process_user($uid);

    // If the group role revoked has a corresponding drupal role, and
    // the user is not entitled to it from another group.
    if ($group_role_map[$rid] && !in_array($group_role_map[$rid], $all_user_roles)) {
      ktc_users_roles_role($uid, $group_role_map[$rid], 'revoke');
    }
  }
}

/**
 * Implements hook_og_membership_delete().
 */
function ktc_users_roles_og_membership_delete($og_membership) {
  $account = user_load($uid);
  $edit['roles'] = $account->roles;

  if ($edit['roles']) {
    $never_remove = variable_get('ktc_users_roles_never_remove', array());

    foreach ($edit['roles'] as $rid) {
      if (!in_array($rid, $never_remove)) {
        unset($edit['roles'][$rid]);
      }
    }

    user_save($account, $edit);
  }
}

/**
 * Handle users role.
 */
function ktc_users_roles_role($uid, $drupal_role_id, $action) {
  $account = user_load($uid);
  $edit['roles'] = $account->roles;

  switch ($action) {
    case 'grant':
      $edit['roles'][$drupal_role_id] = $drupal_role_id;
      break;

    case 'revoke':
      unset($edit['roles'][$drupal_role_id]);
      break;
  }

  user_save($account, $edit);
}

/**
 * Get group nids for a grouptype.
 */
function ktc_users_roles_get_group_nids_by_type($tid) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'group')
    ->fieldCondition('field_netvaerkstype', 'tid', $tid);
  $result = $query->execute();

  if (isset($result['node'])) {
    return array_keys($result['node']);
  }

  return array();
}
