<?php
/**
 * @file
 * KTC Users roles module.
 */

/**
 * Implements hook_menu().
 */
function ktc_users_roles_menu() {
  $items['admin/people/permissions/ktc_users_roles'] = array(
    'title' => 'KTC Users roles',
    'descripiton' => '',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer user permissions'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_users_roles_page'),
  );
  return $items;
}

/**
 * Page callback for settings.
 */
function ktc_users_roles_page() {
  $group_nids = og_get_all_group();

  $group_options[0] = t('- Ingen -');
  foreach ($group_nids as $group_nid) {
    $group = node_load($group_nid);

    $group_options[$group_nid] = $group->title;
  }

  asort($group_options);

  $drupal_role_options[0] = t('Ingen');
  $drupal_role_options = array_merge($drupal_role_options, user_roles());

  $form['groups'] = array(
    '#title' => t('Gruppe'),
    '#description' => t('Vælg en gruppe du vil lave en rolle regel for.'),
    '#type' => 'select',
    '#options' => $group_options,
  );

  $form['select_group'] = array(
    '#value' => t('Vælg'),
    '#type' => 'submit',
    '#submit' => array('ktc_users_roles_select_group'),
  );

  $form['role_map'] = array(
    '#tree' => TRUE,
  );

  $role_map = variable_get('ktc_users_roles_map', array());

  $ktc_users_roles_groups = variable_get('ktc_users_roles_groups', array());
  foreach ($ktc_users_roles_groups as $group_nid) {
    $group = node_load($group_nid);

    $form['role_map'][$group_nid] = array(
      '#type' => 'fieldset',
      '#title' => $group->title,
    );

    $og_roles = og_roles('node', $group->type, $group->nid);

    foreach ($og_roles as $og_role_id => $og_role_name) {
      $form['role_map'][$group_nid][$og_role_id] = array(
        '#type' => 'select',
        '#prefix' => '<span style="float:left; width: 15%">' . $og_role_name . '</span>',
        '#options' => $drupal_role_options,
        '#default_value' => !empty($role_map) ? $role_map[$group_nid][$og_role_id] : 0,
      );
    }

    $form['role_map'][$group_nid]['select_group'] = array(
      '#value' => t('Fjern'),
      '#type' => 'submit',
      '#group_nid' => $group_nid,
      '#submit' => array('ktc_users_roles_select_group'),
    );
  }

  unset($drupal_role_options[0]);
  $form['ktc_users_roles_never_remove'] = array(
    '#title' => t('Fjern aldrig disse roller.'),
    '#options' => $drupal_role_options,
    '#multiple' => TRUE,
    '#type' => 'checkboxes',
    '#default_value' => variable_get('ktc_users_roles_never_remove', array()),
  );

  $form['submit'] = array(
    '#value' => t('Gem'),
    '#type' => 'submit',
  );

  $form['reset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Nulstil'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['reset']['reset'] = array(
    '#value' => t('Nulstil brugerroller'),
    '#suffix' => t('OBS: Dette nulstiller medlemmerne i gruppens roller til de der er angivet ovenfor. Er der manuelt angivet andre på brugeren vil disse blive fjernet.'),
    '#type' => 'submit',
    '#submit' => array('ktc_users_roles_reset'),
  );

  return $form;
}

/**
 * Add a group to the select groups array.
 */
function ktc_users_roles_select_group(&$form, &$form_state) {
  $ktc_users_roles_groups = variable_get('ktc_users_roles_groups', array());

  if (isset($form_state['clicked_button']['#group_nid'])) {
    $selected_group = $form_state['clicked_button']['#group_nid'];

    unset($ktc_users_roles_groups[$selected_group]);

    // Unset from map aswell.
    $role_map = variable_get('ktc_users_roles_map', array());

    unset($role_map[$selected_group]);

    variable_set('ktc_users_roles_map', $role_map);
  }
  else {
    $selected_group = $form_state['values']['groups'];

    if ($selected_group) {
      $ktc_users_roles_groups[$selected_group] = $selected_group;
    }
  }
  variable_set('ktc_users_roles_groups', $ktc_users_roles_groups);
}

/**
 * Submit handler for settings.
 */
function ktc_users_roles_page_submit(&$form, &$form_state) {
  $role_map = $form_state['values']['role_map'];
  variable_set('ktc_users_roles_map', $role_map);

  $never_remove = $form_state['values']['ktc_users_roles_never_remove'];
  variable_set('ktc_users_roles_never_remove', $never_remove);

  drupal_set_message(t('Indstillingerne er blevet gemt'));

}

/**
 * Reset users roles according to the settings.
 */
function ktc_users_roles_reset(&$form, &$form_state) {
  $role_map = $form_state['values']['role_map'];
  ktc_users_roles_process_role_map($role_map);
}

/**
 * Process role map, in order to be able to map roles.
 */
function ktc_users_roles_process_role_map($role_map) {
  foreach ($role_map as $group_nid => $group_role_map) {
    ktc_users_roles_process_group_role_map($group_nid, $group_role_map);
  }
}

/**
 * Process groups role maps.
 */
function ktc_users_roles_process_group_role_map($group_nid, $group_role_map) {
  $query = db_select('og_users_roles', 'ogur');
  $query->rightJoin('og_membership', 'ogm', 'ogm.etid = ogur.uid');
  $query->fields('ogm')
    ->fields('ogur')
    ->condition('ogm.gid', $group_nid, '=');
  $result = $query->execute()->fetchAll();

  foreach ($group_role_map as $og_role_id => $drupal_role_id) {
    if (is_numeric($drupal_role_id) && $drupal_role_id) {
      foreach ($result as $current_role_info) {
        $uid = $current_role_info->etid;

        $account = user_load($uid);

        if ($current_role_info->rid == $og_role_id) {
          $edit['roles'][$drupal_role_id] = $drupal_role_id;
        }

        user_save($account, $edit);
      }
    }
  }
}

/**
 * Process users accumulated roles according to the assigned group roles.
 */
function ktc_users_roles_process_user($uid) {
  $role_map = variable_get('ktc_users_roles_map', array());

  $user_roles = array();

  foreach ($role_map as $group_nid => $group_role_map) {
    $query = db_select('og_users_roles', 'ogur');
    $query->rightJoin('og_membership', 'ogm', 'ogm.etid = ogur.uid');
    $query->fields('ogm')
      ->fields('ogur')
      ->condition('ogm.gid', $group_nid, '=')
      ->condition('ogm.etid', $uid, '=');
    $result = $query->execute()->fetchAll();

    foreach ($group_role_map as $og_role_id => $drupal_role_id) {
      if (is_numeric($drupal_role_id) && $drupal_role_id) {
        foreach ($result as $current_role_info) {
          if ($current_role_info->rid == $og_role_id) {
            $user_roles[$drupal_role_id] = $drupal_role_id;
          }
        }
      }
    }
  }

  return $user_roles;
}

/**
 * Implements hook_og_role_grant().
 */
function ktc_users_roles_og_role_grant($group_type, $gid, $uid, $rid) {
  $role_map = variable_get('ktc_users_roles_map', array());
  $group_role_map = $role_map[$gid];

  if ($group_role_map[$rid]) {
    ktc_users_roles_role($uid, $group_role_map[$rid], 'grant');
  }

}

/**
 * Implements hook_og_role_revoke().
 */
function ktc_users_roles_og_role_revoke($group_type, $gid, $uid, $rid) {
  $role_map = variable_get('ktc_users_roles_map', array());
  $group_role_map = $role_map[$gid];

  // This is far from optimal, and could probarbly be optimised a bit.
  // Since the user can be member of several groups, that all grant a site
  // wide role, we need to make sure that we do not remove any of the roles
  // that the user is entitled to.
  $all_user_roles = ktc_users_roles_process_user($uid);

  // If the group role revoked has a corresponding drupal role, and
  // the user is not entitled to it from another group.
  if ($group_role_map[$rid] && !in_array($group_role_map[$rid], $all_user_roles)) {
    ktc_users_roles_role($uid, $group_role_map[$rid], 'revoke');
  }
}

/**
 * Implements hook_og_membership_delete().
 */
function ktc_users_roles_og_membership_delete($og_membership) {
  $account = user_load($uid);
  $edit['roles'] = $account->roles;

  if ($edit['roles']) {
    $never_remove = variable_get('ktc_users_roles_never_remove', array());

    foreach ($edit['roles'] as $rid) {
      if (!in_array($rid, $never_remove)) {
        unset($edit['roles'][$rid]);
      }
    }

    user_save($account, $edit);
  }
}

/**
 * Handle users role.
 */
function ktc_users_roles_role($uid, $drupal_role_id, $action) {
  $account = user_load($uid);
  $edit['roles'] = $account->roles;

  switch ($action) {
    case 'grant':
      $edit['roles'][$drupal_role_id] = $drupal_role_id;
      break;

    case 'revoke':
      unset($edit['roles'][$drupal_role_id]);
      break;
  }

  user_save($account, $edit);
}
