<?php
/**
 * @file
 * KTC Hearing attendees module.
 */

/**
 * Implements hook_form_alter().
 */
function ktc_hearing_attendees_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'hearing_node_form') {

    $path = drupal_get_path('module', 'ktc_hearing_attendees');
    drupal_add_js($path . '/ktc_hearing_attendees.js');
    drupal_add_css($path . '/chosen_ajax.css');
    drupal_add_js($path . '/ajax-chosen.js');

  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function ktc_hearing_attendees_field_widget_form_alter(&$element, &$form_state, $context) {
  $show_for_fields = array(
    'field_attendees',
    'field_chairman',
    'field_coordinator',
  );

  if (in_array($element['#field_name'], $show_for_fields)) {
    $element['#suffix'] = '<div class="chosen-entityreference-container"><select class="form-control chosen-entityreference" multiple data-autocomplete-path="' . url($element['#autocomplete_path'], array('absolute' => TRUE)) . '">' . _ktc_hearing_attendees_selected($element) . '</select></div>';
  }
}

/**
 * Return a list of options, already selected.
 */
function _ktc_hearing_attendees_selected($element) {
  $options = '';

  if (!empty($element['#default_value'])) {
    $values = explode(', ', $element['#default_value']);

    foreach ($values as $value) {
      $title = preg_replace("/(.+) \((\d+)\)/", '${1}', $value);
      $id = preg_replace("/(.+) \((\d+)\)/", '${2}', $value);
      $id = $value;

      $options .= '<option selected value="' . $id . '">' .  $title . '</option>' . "\n";
    }
  }

  return $options;
}

/**
 * Implements hook_menu().
 */
function ktc_hearing_attendees_menu() {
  $items['ktc_hearing_attendees/get_group_members'] = array(
    'access callback'   => 'user_is_logged_in',
    'page callback'     => 'ktc_hearing_attendees_get_group_members',
    'delivery callback' => 'drupal_json_output',
  );
  return $items;
}

/**
 * Page callback, get members for group.
 */
function ktc_hearing_attendees_get_group_members($id = NULL) {
  if ($group = node_load($id)) {
    $members = array();
    if ($member_uids = og_get_group_members_properties($group, array(), 'members', 'node')) {
      foreach ($member_uids as $member_uid) {
        $roles = og_get_user_roles('node', $id, $member_uid, $include = TRUE);

        if (in_array($member_uid, array(1, 1974))) {
          continue;
        }

        $account = user_load($member_uid);

        $member_value = $account->name . ' (' . $member_uid . ')';

        if (in_array('member', $roles)) {
          $members['attendees'][$member_value] = $account->name;
        }

        if (in_array('Formand', $roles)) {
          $members['chairman'][$member_value] = $account->name;
        }

        if (in_array('Tovholder', $roles)) {
          $members['coordinator'][$member_value] = $account->name;
        }
      }
    }

    return $members;
  }
  return FALSE;
}
