<?php
/**
 * @file
 * KTC Hearing attendees module.
 */

/**
 * Implements hook_init().
 */
function ktc_hearing_attendees_init() {
  if (current_path() == 'node/add/hearing' || (arg(0) == 'node' && arg(2) == 'edit')) {
    $path = drupal_get_path('module', 'ktc_hearing_attendees');
    drupal_add_js($path . '/ktc_hearing_attendees.js');
    drupal_add_css($path . '/chosen_ajax.css');
    drupal_add_js($path . '/ajax-chosen.js');
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function ktc_hearing_attendees_field_widget_form_alter(&$element, &$form_state, $context) {
  $show_for_fields = array(
    'field_attendees',
  );

  if (isset($element['#field_name']) && in_array($element['#field_name'], $show_for_fields)) {
    $url = url($element['#autocomplete_path'], array('absolute' => TRUE));

    $element['#suffix'] = '<div class="chosen-entityreference-container"><select data-placeholder="Vælg" class="form-control chosen-entityreference ajax" multiple data-autocomplete-path="' . $url . '">' . _ktc_hearing_attendees_selected($element) . '</select></div>';
  }

  $show_for_fields = array(
    'field_chairman',
    'field_coordinator',
  );

  if (isset($element['#field_name']) && in_array($element['#field_name'], $show_for_fields)) {
    $element['#suffix'] = '<div class="chosen-entityreference-container"><select data-placeholder="Vælg" class="form-control chosen-entityreference no-ajax" multiple>' . _ktc_hearing_attendees_selected($element) . '</select></div>';
  }

  $show_for_fields = array(
    'field_responsible_foreman',
    'field_responsible_admin',
  );

  if (isset($element['#field_name']) && in_array($element['#field_name'], $show_for_fields)) {
    $element['#suffix'] = '<div class="chosen-entityreference-container"><select data-placeholder="Vælg" class="form-control chosen-entityreference no-ajax">' . _ktc_hearing_attendees_selected($element) . '</select></div>';
  }
}

/**
 * Return a list of options, already selected.
 */
function _ktc_hearing_attendees_selected($element) {
  $options = '';

  if (!empty($element['#default_value'])) {
    $values = explode(', ', $element['#default_value']);

    foreach ($values as $value) {
      $title = preg_replace("/(.+) \((\d+)\)/", '${1}', $value);
      $id = preg_replace("/(.+) \((\d+)\)/", '${2}', $value);
      $id = $value;

      $options .= '<option selected value="' . $id . '">' .  $title . '</option>' . "\n";
    }
  }

  return $options;
}

/**
 * Implements hook_menu().
 */
function ktc_hearing_attendees_menu() {
  $items['ktc_hearing_attendees/get_group_members'] = array(
    'access callback'   => 'user_is_logged_in',
    'page callback'     => 'ktc_hearing_attendees_get_group_members',
    'delivery callback' => 'drupal_json_output',
  );

  return $items;
}

/**
 * Page callback, get members for group.
 */
function ktc_hearing_attendees_get_group_members($id = NULL) {
  if ($group = node_load($id)) {

    // Figure out tids for Formand and Høringstovholder grouproles, we
    // need this later on.
    $grouproles_vocab = taxonomy_vocabulary_machine_name_load('ktc_netvaerk_grouproles');
    $grouproles = taxonomy_term_load_multiple(array(), array('vid' => $grouproles_vocab->vid));

    foreach ($grouproles as $grouprole) {
      if ($grouprole->name == 'Formand') {
        $foreman_tid = $grouprole->tid;
      }
      if ($grouprole->name == 'Høringstovholder') {
        $coordinator_tid = $grouprole->tid;
      }
    }

    $memberships = og_membership_load_multiple(FALSE, array('gid' => $id, 'entity_type' => 'user'));
    $members = array();

    // Generate an array of members according to their grouprole.
    foreach ($memberships as $membership) {
      $member_uid = $membership->etid;
      $account = user_load($member_uid);

      $member_value = $account->name . ' (' . $member_uid . ')';

      $user_grouprole_tid = FALSE;
      if ($field = field_get_items('og_membership', $membership, 'field_grouprole')) {
        $user_grouprole_tid = $field[0]['target_id'];
      }

      // The user should be foreman.
      if ($user_grouprole_tid == $foreman_tid) {
          $members['chairman'][$member_value] = $account->name;
          $members['responsible-foreman'][$member_value] = $account->name;
      }
      // The user should be chairman.
      if ($user_grouprole_tid == $coordinator_tid) {
        $members['coordinator'][$member_value] = $account->name;
        $members['responsible-admin'][$member_value] = $account->name;
      }

      $members['attendees'][$member_value] = $account->name;
    }
    return $members;
  }
  return FALSE;
}
