<?php

/**
 * @file
 * This file holds the install information for Emoji Scrub.
 */

/**
 * Implements hook_install().
 */
function emoji_scrub_install() {
  $t = get_t();
  drupal_set_message($t("Emoji Scrub settings are available under !link",
    array(
      '!link' => l($t('Administration >> Configuration >> Content >> Emoji Scrub'),
      'admin/config/content/emoji_scrub'),
    )
  ));
}

/**
 * Implements hook_uninstall().
 */
function emoji_scrub_uninstall() {
  db_delete('variable')
    ->condition('name', db_like('emoji_scrub_') . '%', 'LIKE')
    ->execute();
  cache_clear_all('variables', 'cache');
}
