<?php
/**
 * @file
 * KTC CRM integration module.
 */

// Load webservice classes.
module_load_include('php', 'ktc_crm', 'includes/KTC/WebUser/WebUser');
module_load_include('php', 'ktc_crm', 'includes/KTC/Subscription/Subscription');
module_load_include('php', 'ktc_crm', 'includes/KTC/GroupService/GroupService');
module_load_include('php', 'ktc_crm', 'includes/KTC/AccountService/AccountService');

module_load_include('inc', 'ktc_crm', 'ktc_crm.api');
module_load_include('inc', 'ktc_crm', 'ktc_crm.group');
module_load_include('inc', 'ktc_crm', 'ktc_crm.webuser');
module_load_include('inc', 'ktc_crm', 'ktc_crm.account');

define('KTC_CRM_WEBUSER_WSDL', 'WebUser.svc?wsdl');
define('KTC_CRM_SUBSCRIPTION_WSDL', 'Subscription.svc?wsdl');
define('KTC_CRM_GROUPSERVICE_WSDL', 'GroupService.svc?wsdl');
define('KTC_CRM_ACCOUNTSERVICE_WSDL', 'AccountService.svc?wsdl');

/**
 * Implements hook_menu().
 */
function ktc_crm_menu() {
  $items['admin/config/services/ktc-crm'] = array(
    'title' => 'KTC CRM',
    'description' => 'Configure CRM integration',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_crm_settings'),
    'type' => MENU_NORMAL_ITEM | MENU_LOCAL_TASK,
  );

   $items['user/%/ktc_crm_sync'] = array(
    'title' => 'Bruger CRM sync',
    'description' => 'This is the fallback for synching using to/from CRM',
    'access arguments' => array('administer users'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ktc_crm_user_sync_page'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ktc_crm_theme() {
  return array(
    'ktc_crm_subscriptions_page' => array(
      'template' => 'ktc-crm-subscriptions-page',
    ),
  );
}

/**
 * Implements hook_permissions().
 */
function ktc_crm_permission() {
  return array(
    'administer ktc_crm' => array(
      'title' => t('Administer KTC CRM'),
      'description' => t('Perform various administration tasks KTC CRM module.'),
    ),
  );
}

/**
 * Form callback for settings.
 */
function ktc_crm_settings() {
  $form = array();

  $form['ktc_crm_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Endpoint url'),
    '#default_value' => variable_get('ktc_crm_url', ''),
  );

  return system_settings_form($form);
}

/**
  * Page callback to ktc_crm_sync menu item
  */
function ktc_crm_user_sync_page($form, &$form_state) {
  $form = array();

  $uid = arg(1);
  $active_user = user_load($uid);

  if ($active_user) {
    $form['ktc_update_user_from_crm'] = array(
      '#type' => 'submit',
      '#value' => t('Update user from CRM'),
      '#submit' => array('ktc_crm_user_synch_page_submit_from_crm')
    );

    $form['ktc_update_user_to_crm'] = array(
      '#type' => 'submit',
      '#value' => t('Save user information into CRM'),
      '#submit' => array('ktc_crm_user_synch_page_submit_to_crm')
    );
  }
  
  return $form;
}

/**
  * Update user from CRM submit function
  */
function ktc_crm_user_synch_page_submit_from_crm($form, &$form_state) {
  $uid = arg(1);
  $active_user = user_load($uid);

  $batch = array(
    'operations' => array(array('ktc_crm_user_synch_page_submit_from_crm_process', array($active_user))),
    'finished' => 'ktc_crm_user_synch_page_submit_from_crm_finished',
    'title' => t('Batch fix'),
    'init_message' => t('Starting loading user from CRM...'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Encountered an error.')
  );

  batch_set($batch);
  batch_process('user/' . $uid . '/ktc_crm_sync'); // The path to redirect to when done.
}

/**
  * Update user from CRM batch process function
  */
function ktc_crm_user_synch_page_submit_from_crm_process($user, &$context) {
  $webuserdto = ktc_crm_lookup_webuser_by_mail($user->mail);
  ktc_crm_update_account_from_webuserdto($webuserdto);

  $context['message'] = t('Loading user "@username" from CRM', array('@username' => $user->name));
}

/**
  * Update user from CRM batch finished function
  */
function ktc_crm_user_synch_page_submit_from_crm_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message('Successfully loaded user from CRM');
  }
  else {
    $error_operation = reset($operations);
    $message = t('An error occurred while processing %error_operation with arguments: @arguments', array(
      '%error_operation' => $error_operation[0],
      '@arguments' => print_r($error_operation[1], TRUE)
    ));
    drupal_set_message($message, 'error');
  }
}

/**
  * Save user information into CRM submit function
  */
function ktc_crm_user_synch_page_submit_to_crm($form, &$form_state) {
  $uid = arg(1);
  $active_user = user_load($uid);

  if (field_get_items('user', $active_user, 'field_crm_uuid')) {
    $batch = array(
      'operations' => array(array('ktc_crm_user_synch_page_submit_to_crm_process', array($active_user))),
      'finished' => 'ktc_crm_user_synch_page_submit_to_crm_finished',
      'title' => t('Batch fix'),
      'init_message' => t('Starting uploading user into CRM...'),
      'progress_message' => t('Processed @current out of @total.'),
      'error_message' => t('Encountered an error.')
    );

    batch_set($batch);
    batch_process('user/' . $uid . '/ktc_crm_sync'); // The path to redirect to when done.
  } else {
    drupal_set_message('Cannot store user information into CRM, UUID is missing', 'warning');
  }
}

/**
  * Save user information into CRM batch process function
  */
function ktc_crm_user_synch_page_submit_to_crm_process($user, &$context) {
  $webuserdto = ktc_crm_map_account_to_webuserdto($user);
  ktc_crm_update_user($webuserdto);

  $context['message'] = t('Uploading user "@username" into CRM', array('@username' => $user->name));
}

/**
  * Save user information into CRM batch finish function
  */
function ktc_crm_user_synch_page_submit_to_crm_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message('Successfully uploaded user info into CRM');
  }
  else {
    $error_operation = reset($operations);
    $message = t('An error occurred while processing %error_operation with arguments: @arguments', array(
      '%error_operation' => $error_operation[0],
      '@arguments' => print_r($error_operation[1], TRUE)
    ));
    drupal_set_message($message, 'error');
  }
}

/**
 * Implements hook_form_alter().
 */
function ktc_crm_form_alter(&$form, &$form_state, $form_id) {
  // We have no interest in lettings users edit this.
  if (!user_access('administer ktc_crm')) {
    if ($form_id == 'user_profile_form') {
      $form['field_crm_uuid']['#access'] = FALSE;
    }

    if ($form_id == 'og_ui_add_users') {
      $form['membership_fields']['field_crm_uuid']['#access'] = FALSE;
    }

    if ($form_id == 'group_node_form' || $form_id == 'og_ui_confirm_subscribe') {
      $form['field_crm_uuid']['#access'] = FALSE;
    }
  }
}

/**
 * Helper, fetch enity crm uuid.
 */
function _ktc_crm_get_uuid($type, $entity) {
  if ($entity !== FALSE) {
    if ($crm_uuid_field = field_get_items($type, $entity, 'field_crm_uuid')) {
      $crm_uuid = $crm_uuid_field[0]['value'];

      if (strlen($crm_uuid)) {
        return strtolower($crm_uuid);
      }
    }
  }
  return FALSE;
}

/**
 * Helper, fetch term name from tid.
 */
function _ktc_crm_get_term_name($tid) {
  if ($term = taxonomy_term_load($tid)) {
    return $term->name;
  }
  return FALSE;
}

/**
 * Helper, translitterate stings.
 */
function _ktc_crm_translitterate($text) {
  return str_replace(array('æ', 'ø', 'å'), array('ae', 'oe', 'aa'), $text);
}

/**
 * Helper, is the user a KTC member.
 */
function _ktc_crm_is_ktc_member() {
  return FALSE;
}

use Monolog\Logger;
use Monolog\Handler\StreamHandler;

class KtcCrmLogger {

  private static $instance;

  public $log;

  /**
   * Create instance of logger.
   */
  private function __construct() {
    $log_path = variable_get('ktc_crm_sync_log_path', '/var/www/logs/crm_sync.log');
    $log_level = Logger::INFO;

    if (variable_get('ktc_crm_sync_log_verbose', FALSE)) {
      $log_level = Logger::DEBUG;
    }

    // We need to load module here in order to make sure that composer manager autoloader is ready
    module_load_include('php', 'ktc_crm', 'includes/KtcCrmLoggerToWatchdogHandler');
    $this->log = new Logger('ktc_crm_sync');
    $this->log->pushHandler(new StreamHandler($log_path, $log_level));
    $this->log->pushHandler(new KtcCrmLoggerToWatchdogHandler($log_level));
  }

  /**
   * Return instance of logger.
   */
  public static function getInstance() {
    if (empty(self::$instance)) {
      $class = __CLASS__;
      self::$instance = new $class();
    }

    return self::$instance;
  }
}
