<?php
/**
 * @file
 * ktc_netvaerk_notifications.module
 */

/**
 * Implements hook_menu().
 */
function ktc_netvaerk_notifications_menu() {
  $items['admin/netvaerk_setting/notifications'] = array(
    'title' => 'Notifikationer',
    'description' => 'Configure group notifications',
    'page_callback' => 'drupal_get_form',
    'page arguments' => array('ktc_netvaerk_notifications_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function ktc_netvaerk_notifications_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    // Unset groups the user is not member of.
    // Get the users groups.
    $options = og_get_groups_by_user($form['#entity'], 'node');

    // Get the current selected options. We don't wan't to unset these.
    $default_value = $form['field_netvaerk_notifications'][LANGUAGE_NONE]['#default_value'];
    foreach ($default_value as $_val) {
      $options[$_val] = $_val;
    }

    // The actual unsetting.
    foreach ($form['field_netvaerk_notifications'][LANGUAGE_NONE]['#options'] as $gid => $value) {
      if (!is_array($options) || !in_array($gid, $options)) {
        unset($form['field_netvaerk_notifications'][LANGUAGE_NONE]['#options'][$gid]);
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function ktc_netvaerk_notifications_block_info() {
  $blocks['current_groups'] = array(
    'info' => t('KTC Netværk notifikationer - grupper'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ktc_netvaerk_notifications_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'current_groups':
      $block['content'] = ktc_netvaerk_notifications_current_groups();
      break;
  }
  return $block;
}

/**
 * Generate a list of the groups that the current user is subscribing to.
 */
function ktc_netvaerk_notifications_current_groups() {
  if (arg(0) == 'user' && is_numeric(arg(1))) {
    $account = user_load(arg(1));
  }
  else {
    global $user;
    $account = user_load($user->uid);
  }

  // Fetch users notification groups and group memberships.
  $notify_groups = array();
  $member_groups = array();
  if ($field = field_get_items('user', $account, 'field_netvaerk_notifications')) {
    foreach ($field as $delta => $value) {
      $nid = $value['target_id'];
      $notify_groups[$nid] = $nid;
    }
  }
  if ($field = field_get_items('user', $account, 'og_user_node')) {
    foreach ($field as $delta => $value) {
      $nid = $value['target_id'];
      $member_groups[$nid] = _ktc_netvaerk_notifications_get_node_title($nid);
    }
  }

  // Sort and then mark the groups with notifications active.
  asort($member_groups);
  foreach ($member_groups as $nid => $title) {
    if (in_array($nid, $notify_groups)) {
      $class = 'glyphicon glyphicon-star';
    }
    else {
      $class = 'glyphicon glyphicon-spacer';
    }
    $member_groups[$nid] = '<div class="list-item"><span class="' . $class . '"></span> ' . $title . '</div>';
  }

  $markup = implode('', $member_groups);
  $markup .= '<p><a href="/user/' . $account->uid . '/edit" class="btn btn-default"><span class="glyphicon glyphicon-star"></span> Rediger netværks-notifikationer</a></p>';

  return $markup;
}

/**
 * Admin settings form.
 */
function ktc_netvaerk_notifications_settings() {
  $form = array();

  $form['ktc_netvaerk_notifications_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Emne'),
    '#default_value' => variable_get('ktc_netvaerk_notifications_subject'),
  );

  $form['ktc_netvaerk_notifications_body'] = array(
    '#type' => 'textarea',
    '#title' => t('Besked'),
    '#default_value' => variable_get('ktc_netvaerk_notifications_body'),
  );

  $form['tokens'] = array(
    '#theme' => 'token_tree',
    '#token_types' => array('user', 'node'),
    '#global_types' => FALSE,
    '#click_insert' => FALSE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_mail().
 */
function ktc_netvaerk_notifications_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}

/**
 * Implements hook_node_presave().
 */
function ktc_netvaerk_notifications_node_presave($node) {
  if (is_object($node) && $node->nid && $node->status && $field = field_get_items('node', $node, 'og_group_ref')) {
    if ($node->type == 'hearing' || $node->type == 'hearing_responses') {
      return;
    }

    $result = db_query('SELECT status FROM {ktc_netvaerk_notifications} WHERE nid = :nid', array(':nid' => $node->nid))->fetchAll();

    if (empty($result)) {
      db_insert('ktc_netvaerk_notifications')
        ->fields(array(
          'nid' => $node->nid,
          'status' => 1,
        ))
        ->execute();

      $field = reset($field);
      $group_id = $field['target_id'];

      $uids = _ktc_netvaerk_notifications_get_users($group_id);

      foreach ($uids as $uid) {
        $user = user_load($uid);

        $token_data = array('user' => $user, 'node' => $node);
        $to = $user->mail;

        // Testing.
        $to = 'tth@bellcom.dk';
        $language = $user->language;

        $params = array();
        $params['subject'] = token_replace(variable_get('ktc_netvaerk_notifications_subject'), $token_data);
        $params['body'] = token_replace(variable_get('ktc_netvaerk_notifications_body'), $token_data);

        drupal_mail('ktc_netvaerk_notifications', 'notify_new', $to, $language, $params);
      }
    }
  }
}

/**
 * Get a list of users to notify for the content node.
 */
function ktc_netvaerk_notifications_content_get_users($node) {
  if (is_object($node) && $field = field_get_items('node', $node, 'og_group_ref')) {
    $group_id = $field[0]['target_id'];
    return _ktc_netvaerk_notifications_get_users($group_id);
  }
  return array();
}

/**
 * Determine if the user should retrieve notifications for a given node.
 */
function ktc_netvaerk_notifications_notify_for_node($node, $uid) {
  if ($field = field_get_items('node', $node, 'og_group_ref')) {
    $group_id = $field[0]['target_id'];

    $notify_uids = _ktc_netvaerk_notifications_get_users($group_id);

    if (in_array($uid, $notify_uids)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Helper function to get the node title.
 */
function _ktc_netvaerk_notifications_get_node_title($nid) {
  return db_query('SELECT title FROM {node} WHERE nid = :nid', array(':nid' => $nid))->fetchField();
}

/**
 * Get a list of users to notify.
 */
function _ktc_netvaerk_notifications_get_users($group_id) {
  // Get a list of users who want notifications for this group.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'user')
     ->fieldCondition('field_netvaerk_notifications', 'target_id', $group_id);
  $result = $query->execute();

  if (isset($result['user'])) {
    return array_keys($result['user']);
  }
  return array();
}
